import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { program_id, date_range_days = 30 } = await req.json().catch(() => ({}));

    // Get all programs managed by this user
    const allPrograms = await base44.entities.Program.list();
    const managedPrograms = allPrograms.filter(p => 
      p.manager_emails?.includes(user.email) || 
      p.primary_manager_email === user.email ||
      p.program_manager_email === user.email
    );

    if (managedPrograms.length === 0) {
      return Response.json({ error: 'No programs found' }, { status: 404 });
    }

    // Filter by specific program if provided
    const programsToAnalyze = program_id 
      ? managedPrograms.filter(p => p.id === program_id)
      : managedPrograms;

    const programIds = programsToAnalyze.map(p => p.id);

    // Get cohorts and participants
    const allCohorts = await base44.entities.Cohort.list();
    const programCohorts = allCohorts.filter(c => programIds.includes(c.program_id));

    const participantEmails = new Set();
    programsToAnalyze.forEach(p => {
      p.participant_emails?.forEach(e => participantEmails.add(e));
    });
    programCohorts.forEach(c => {
      c.participant_emails?.forEach(e => participantEmails.add(e));
    });

    // Date filter
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - date_range_days);

    // Fetch data
    const [allGoals, allAssessments, allLearning] = await Promise.all([
      base44.entities.Goal.list(),
      base44.entities.Assessment.list(),
      base44.entities.AssignedLearning.list()
    ]);

    // Filter data
    const programGoals = allGoals.filter(g => 
      (programIds.includes(g.program_id) || participantEmails.has(g.created_by)) &&
      new Date(g.created_date) >= cutoffDate
    );

    const programAssessments = allAssessments.filter(a => 
      participantEmails.has(a.email) &&
      new Date(a.submission_ts || a.created_date) >= cutoffDate
    );

    const programLearning = allLearning.filter(l => 
      participantEmails.has(l.user_email) &&
      new Date(l.created_date) >= cutoffDate
    );

    // Calculate metrics
    const totalGoals = programGoals.length;
    const completedGoals = programGoals.filter(g => g.status === 'archived' || g.progress === 100).length;
    const goalCompletionRate = totalGoals > 0 ? Math.round((completedGoals / totalGoals) * 100) : 0;

    const totalAssessments = programAssessments.length;
    const avgAssessmentScore = totalAssessments > 0 
      ? Math.round(programAssessments.reduce((sum, a) => sum + (a.overall_pct || 0), 0) / totalAssessments)
      : 0;

    const totalLearning = programLearning.length;
    const completedLearning = programLearning.filter(l => l.status === 'completed').length;
    const learningCompletionRate = totalLearning > 0 ? Math.round((completedLearning / totalLearning) * 100) : 0;

    // Generate PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(2, 2, 255);
    doc.text('Program Performance Report', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()} | Date Range: Last ${date_range_days} days`, pageWidth / 2, 28, { align: 'center' });
    doc.text(`Generated by: ${user.full_name}`, pageWidth / 2, 34, { align: 'center' });

    // Summary Section
    let y = 50;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Executive Summary', 20, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.text(`Total Programs: ${programsToAnalyze.length}`, 20, y);
    y += 6;
    doc.text(`Total Participants: ${participantEmails.size}`, 20, y);
    y += 6;
    doc.text(`Total Goals: ${totalGoals} (${completedGoals} completed - ${goalCompletionRate}%)`, 20, y);
    y += 6;
    doc.text(`Average Assessment Score: ${avgAssessmentScore}%`, 20, y);
    y += 6;
    doc.text(`Learning Completion Rate: ${learningCompletionRate}%`, 20, y);

    // Program Breakdown
    y += 15;
    doc.setFontSize(14);
    doc.text('Program Breakdown', 20, y);

    y += 10;
    doc.setFontSize(9);

    // Table headers
    doc.setFillColor(240, 240, 240);
    doc.rect(20, y - 4, pageWidth - 40, 8, 'F');
    doc.text('Program', 22, y);
    doc.text('Participants', 80, y);
    doc.text('Goals', 110, y);
    doc.text('Completion', 140, y);
    doc.text('Status', 170, y);

    y += 8;

    programsToAnalyze.forEach(program => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      const pGoals = programGoals.filter(g => g.program_id === program.id);
      const pCompleted = pGoals.filter(g => g.status === 'archived' || g.progress === 100).length;
      const pRate = pGoals.length > 0 ? Math.round((pCompleted / pGoals.length) * 100) : 0;

      doc.text(program.name?.substring(0, 25) || 'N/A', 22, y);
      doc.text(String(program.participant_emails?.length || 0), 80, y);
      doc.text(String(pGoals.length), 110, y);
      doc.text(`${pRate}%`, 140, y);
      doc.text(program.status || 'draft', 170, y);

      y += 6;
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
      doc.text('Curiosity Led - Leadership Development Platform', pageWidth / 2, 295, { align: 'center' });
    }

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=program-performance-report-${new Date().toISOString().split('T')[0]}.pdf`
      }
    });
  } catch (error) {
    console.error('Error in exportProgramPerformancePDF:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});