import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });

    const { to_email, name, overall, band, archetype, current_role, sector, dna_description, comp_keys, assessment, blind_spot_primary } = await req.json();

    if (!to_email) return Response.json({ error: "to_email required" }, { status: 400 });

    const compRows = (comp_keys || []).map(c => {
      const score = assessment?.[c.key];
      if (score == null) return "";
      const b = score >= 80 ? "Mastery" : score >= 65 ? "Proficient" : score >= 50 ? "Developing" : "Awareness";
      return `<tr><td style="padding:8px 12px;border-top:1px solid #f3f4f6;">${c.full}</td><td style="padding:8px 12px;border-top:1px solid #f3f4f6;text-align:right;font-weight:600;color:#0012ff;">${score}%</td><td style="padding:8px 12px;border-top:1px solid #f3f4f6;text-align:right;color:#6b7280;">${b}</td></tr>`;
    }).join("");

    const body = `
<div style="font-family:sans-serif;max-width:640px;margin:auto;padding:32px;border:1px solid #e5e7eb;border-radius:12px;">
  <div style="background:linear-gradient(to right,#0012ff,#3b30ff);border-radius:10px;padding:24px 28px;margin-bottom:24px;">
    <h1 style="color:#fff;font-size:22px;margin:0 0 4px;">${name}</h1>
    <p style="color:#c7d2fe;font-size:13px;margin:0;">${current_role || ""}${sector ? " · " + sector : ""}</p>
    <div style="margin-top:16px;display:flex;align-items:baseline;gap:12px;">
      <span style="color:#fff;font-size:36px;font-weight:800;">${overall}%</span>
      <span style="color:#c7d2fe;font-size:14px;">Leadership Index · ${band}</span>
    </div>
    ${archetype ? `<div style="margin-top:10px;"><span style="background:rgba(255,255,255,0.2);color:#fff;padding:4px 12px;border-radius:20px;font-size:13px;">${archetype}</span></div>` : ""}
  </div>

  ${dna_description ? `<div style="background:#f0f4ff;border-left:4px solid #0012ff;padding:14px 18px;border-radius:6px;margin-bottom:20px;font-size:14px;color:#374151;font-style:italic;">"${dna_description}"</div>` : ""}

  <h2 style="font-size:15px;color:#111;margin-bottom:12px;">Leadership Competency Breakdown</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px;">
    <tr style="background:#f9fafb;"><th style="text-align:left;padding:8px 12px;color:#6b7280;">Competency</th><th style="text-align:right;padding:8px 12px;color:#6b7280;">Score</th><th style="text-align:right;padding:8px 12px;color:#6b7280;">Level</th></tr>
    ${compRows}
  </table>

  ${blind_spot_primary ? `
  <h2 style="font-size:15px;color:#111;margin-bottom:8px;">Primary Development Focus</h2>
  <div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:14px 18px;margin-bottom:20px;">
    <p style="font-weight:600;color:#c2410c;margin:0 0 6px;">${blind_spot_primary.title}</p>
    <p style="font-size:13px;color:#374151;margin:0;">${blind_spot_primary.why_it_happens}</p>
  </div>` : ""}

  <p style="font-size:12px;color:#9ca3af;margin-top:24px;border-top:1px solid #f3f4f6;padding-top:16px;">Shared via Curiosity Led Leadership Development Platform · Full report generated by AI</p>
</div>`.trim();

    await base44.asServiceRole.integrations.Core.SendEmail({
      to: to_email,
      subject: `${name}'s Full Leadership Profile Report`,
      body,
    });

    return Response.json({ success: true });
  } catch (error) {
    console.error("shareLeadershipProfile error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});