
import React, { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Alert, AlertDescription } from "@/components/ui/alert";
import UserComboBox from "@/components/onboarding/UserComboBox";
import { useAuth } from "@/components/useAuth";
import { base44 } from "@/api/base44Client";
import { Mail, X, Users, Loader2, AlertCircle, FileText } from "lucide-react";
import { toast } from "sonner";

export default function ShareStrategicAnalysisModal({ isOpen, onClose, analysisContent, actionPlan, riskData }) {
  const { user, hasRole, hasPermission } = useAuth();
  
  const [recipients, setRecipients] = useState([]);
  const [manualEmail, setManualEmail] = useState("");
  const [customMessage, setCustomMessage] = useState("");
  const [includeOptions, setIncludeOptions] = useState({
    analysis: true,
    actionPlan: true,
    progressNotes: false
  });
  const [sendCopyToSelf, setSendCopyToSelf] = useState(false);
  const [loading, setLoading] = useState(false);
  const [emailError, setEmailError] = useState("");

  // Permission checks
  const canShareWithTeam = hasRole(['User Level 2', 'User Level 3', 'Admin Level 1', 'Admin Level 2', 'Admin Level 3']);
  const canShareWithAnyone = hasRole(['Admin Level 1', 'Admin Level 2', 'Admin Level 3']);

  useEffect(() => {
    if (isOpen && riskData) {
      setCustomMessage(`I wanted to share this strategic analysis with you regarding: ${riskData.title}`);
    }
  }, [isOpen, riskData]);

  const validateEmail = (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  const handleAddManualEmail = () => {
    const trimmedEmail = manualEmail.trim();
    
    if (!trimmedEmail) {
      setEmailError('Please enter an email address');
      return;
    }

    if (!validateEmail(trimmedEmail)) {
      setEmailError('Please enter a valid email address');
      return;
    }

    if (recipients.includes(trimmedEmail)) {
      setEmailError('This email is already in the recipient list');
      return;
    }

    if (trimmedEmail === user.email) {
      setEmailError('You cannot add yourself as a recipient (use "Send copy to self" instead)');
      return;
    }

    setRecipients([...recipients, trimmedEmail]);
    setManualEmail("");
    setEmailError("");
  };

  const handleRemoveRecipient = (email) => {
    setRecipients(recipients.filter(e => e !== email));
  };

  const handleUserComboBoxSelect = (email) => {
    if (email && !recipients.includes(email) && email !== user.email) {
      setRecipients([...recipients, email]);
    }
  };

  const buildEmailContent = () => {
    let content = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%); padding: 30px; border-radius: 10px 10px 0 0;">
          <h2 style="color: white; margin: 0;">Strategic Analysis Shared</h2>
          <p style="color: rgba(255,255,255,0.9); margin-top: 10px;">From ${user.full_name}</p>
        </div>

        <div style="background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 10px 10px;">
    `;

    if (customMessage) {
      content += `
        <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <p style="color: #374151; margin: 0; line-height: 1.6;">${customMessage}</p>
        </div>
      `;
    }

    if (includeOptions.analysis && analysisContent) {
      content += `
        <h3 style="color: #1f2937; margin-top: 20px;">Strategic Analysis</h3>
        <div style="background: #f9fafb; padding: 15px; border-radius: 8px; margin-top: 10px;">
          <p style="color: #4b5563; white-space: pre-line; line-height: 1.6;">${analysisContent}</p>
        </div>
      `;
    }

    if (includeOptions.actionPlan && actionPlan) {
      content += `
        <h3 style="color: #1f2937; margin-top: 20px;">Action Plan</h3>
        <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; margin-top: 10px; border-left: 4px solid #10b981;">
          <p style="color: #065f46; white-space: pre-line; line-height: 1.6;">${actionPlan}</p>
        </div>
      `;
    }

    content += `
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;"/>
          <p style="color: #6b7280; font-size: 14px;">
            This strategic analysis was generated by Atreus, the AI Strategic Decision Assistant on the Curiosity Led platform.
          </p>
        </div>
      </div>
    `;

    return content;
  };

  const handleShare = async () => {
    if (recipients.length === 0) {
      toast.error('Please add at least one recipient');
      return;
    }

    if (!includeOptions.analysis && !includeOptions.actionPlan) {
      toast.error('Please select at least one item to include');
      return;
    }

    setLoading(true);
    try {
      const emailContent = buildEmailContent();
      const emailSubject = riskData?.title 
        ? `Strategic Analysis: ${riskData.title}`
        : 'Strategic Analysis Shared With You';

      const allRecipients = sendCopyToSelf ? [...recipients, user.email] : recipients;

      // Send emails
      const emailPromises = allRecipients.map(email =>
        base44.integrations.Core.SendEmail({
          to: email,
          subject: emailSubject,
          body: emailContent,
          from_name: `${user.full_name} via Curiosity Led`
        })
      );

      await Promise.all(emailPromises);

      toast.success(`Analysis shared with ${recipients.length} recipient(s)`);
      onClose();
    } catch (error) {
      console.error('Error sharing analysis:', error);
      toast.error('Failed to share analysis');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="text-xl flex items-center gap-2">
            <Mail className="w-5 h-5 text-green-600" />
            Share Strategic Analysis
          </DialogTitle>
          <p className="text-sm text-gray-600">Send this analysis to team members or stakeholders</p>
        </DialogHeader>

        <ScrollArea className="flex-1 pr-4">
          <div className="space-y-6">
            {/* Recipients Section */}
            <div>
              <Label className="mb-2 block">Recipients</Label>
              
              {/* User ComboBox */}
              {canShareWithTeam && (
                <div className="mb-3">
                  <UserComboBox
                    value=""
                    onValueChange={handleUserComboBoxSelect}
                    placeholder="Select from organization users..."
                    currentUserEmail={user.email}
                  />
                </div>
              )}

              {/* Manual Email Entry */}
              <div className="flex gap-2 mb-3">
                <Input
                  type="email"
                  placeholder="Or enter email address..."
                  value={manualEmail}
                  onChange={(e) => {
                    setManualEmail(e.target.value);
                    setEmailError("");
                  }}
                  onKeyPress={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleAddManualEmail();
                    }
                  }}
                  className={emailError ? "border-red-500" : ""}
                />
                <Button onClick={handleAddManualEmail} size="sm">
                  Add
                </Button>
              </div>

              {emailError && (
                <p className="text-red-500 text-sm mb-3">{emailError}</p>
              )}

              {/* Selected Recipients */}
              {recipients.length > 0 && (
                <div className="flex flex-wrap gap-2 p-3 bg-gray-50 rounded-lg">
                  {recipients.map((email) => (
                    <Badge key={email} variant="secondary" className="flex items-center gap-2">
                      {email}
                      <button
                        onClick={() => handleRemoveRecipient(email)}
                        className="hover:bg-gray-300 rounded-full p-0.5"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              )}
            </div>

            {/* Permission Warning */}
            {!canShareWithTeam && (
              <Alert className="border-blue-200 bg-blue-50">
                <AlertCircle className="w-4 h-4 text-blue-600" />
                <AlertDescription className="text-blue-900 text-sm">
                  You can share with any email address. For organizational users, contact your manager for access to the user directory.
                </AlertDescription>
              </Alert>
            )}

            {/* Include Options */}
            <div>
              <Label className="mb-3 block">Include in Email</Label>
              <div className="space-y-3">
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="include-analysis"
                    checked={includeOptions.analysis}
                    onCheckedChange={(checked) => 
                      setIncludeOptions(prev => ({ ...prev, analysis: checked }))
                    }
                    disabled
                  />
                  <label htmlFor="include-analysis" className="text-sm cursor-pointer flex items-center gap-2">
                    <FileText className="w-4 h-4 text-purple-600" />
                    Strategic Analysis (Required)
                  </label>
                </div>

                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="include-action"
                    checked={includeOptions.actionPlan}
                    onCheckedChange={(checked) => 
                      setIncludeOptions(prev => ({ ...prev, actionPlan: checked }))
                    }
                  />
                  <label htmlFor="include-action" className="text-sm cursor-pointer flex items-center gap-2">
                    <FileText className="w-4 h-4 text-blue-600" />
                    Action Plan
                  </label>
                </div>
              </div>
            </div>

            {/* Custom Message */}
            <div>
              <Label className="mb-2 block">Personal Message (Optional)</Label>
              <Textarea
                value={customMessage}
                onChange={(e) => setCustomMessage(e.target.value)}
                placeholder="Add a personal note to your email..."
                rows={3}
              />
              <p className="text-xs text-gray-500 mt-1">
                {customMessage.length}/500 characters
              </p>
            </div>

            {/* Send Copy to Self */}
            <div className="flex items-center space-x-2">
              <Checkbox
                id="copy-self"
                checked={sendCopyToSelf}
                onCheckedChange={setSendCopyToSelf}
              />
              <label htmlFor="copy-self" className="text-sm cursor-pointer">
                Send a copy to myself
              </label>
            </div>

            {/* Preview */}
            {recipients.length > 0 && (
              <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                <p className="text-sm font-medium text-green-900 mb-1">Ready to Send:</p>
                <p className="text-sm text-green-800">
                  {recipients.length} recipient(s) will receive this strategic analysis{sendCopyToSelf && ' (+ yourself)'}.
                </p>
              </div>
            )}
          </div>
        </ScrollArea>

        <DialogFooter className="flex-shrink-0 mt-4">
          <Button variant="outline" onClick={onClose} disabled={loading}>
            Cancel
          </Button>
          <Button onClick={handleShare} disabled={loading} className="bg-green-600 hover:bg-green-700">
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Sending...
              </>
            ) : (
              <>
                <Mail className="w-4 h-4 mr-2" />
                Send to {recipients.length} Recipient{recipients.length !== 1 ? 's' : ''}
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
