import { createClientFromRequest } from 'npm:@base44/sdk@0.7.1';
import { jsPDF } from 'npm:jspdf@2.5.1';

/**
 * Generates a comprehensive PDF export of Enterprise Leadership Analytics
 */
Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();
        
        if (!user) {
            return Response.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        }

        // Check permissions - only organizational leaders and admins can export
        const hasAccess = ['User Level 3', 'Admin Level 2', 'Super Administrator', 'Platform Admin'].includes(user.app_role);
        
        if (!hasAccess) {
            return Response.json({ 
                success: false, 
                error: 'Insufficient permissions to export analytics' 
            }, { status: 403 });
        }

        const { stats, divisions, timeRange } = await req.json();
        
        if (!stats) {
            return Response.json({ 
                success: false, 
                error: 'Analytics data is required' 
            }, { status: 400 });
        }

        // Create PDF
        const doc = new jsPDF();
        let yPosition = 20;
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;
        const margin = 20;
        const maxWidth = pageWidth - (margin * 2);

        // Helper function to add new page if needed
        const checkPageBreak = (neededSpace = 20) => {
            if (yPosition + neededSpace > pageHeight - margin) {
                doc.addPage();
                yPosition = margin;
                return true;
            }
            return false;
        };

        // Header with Logo Area
        doc.setFontSize(24);
        doc.setTextColor(30, 64, 175); // Blue
        doc.text('Enterprise Leadership Analytics', margin, yPosition);
        
        yPosition += 10;
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated: ${new Date().toLocaleDateString()} | Time Range: ${timeRange || '6 months'}`, margin, yPosition);
        doc.text(`Generated by: ${user.full_name}`, pageWidth - margin - 60, yPosition);
        
        yPosition += 15;

        // Executive Summary Section
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Executive Summary', margin, yPosition);
        
        yPosition += 10;
        
        // Key Metrics Grid
        const metricsData = [
            { label: 'Total Leaders', value: stats.total_leaders || 0 },
            { label: 'Avg SI Score', value: `${stats.avg_si_score || 0}%` },
            { label: 'Bench Strength', value: `${stats.bench_strength || 0}%` },
            { label: 'Ready Now', value: stats.ready_now || 0 },
            { label: 'High Potential', value: stats.high_potential || 0 },
            { label: 'At Risk', value: stats.at_risk || 0 },
            { label: 'Pipeline Strength', value: `${stats.pipeline_strength || 0}%` }
        ];

        doc.setFontSize(10);
        const cols = 4;
        const colWidth = maxWidth / cols;
        const rowHeight = 25;
        
        metricsData.forEach((metric, idx) => {
            const col = idx % cols;
            const row = Math.floor(idx / cols);
            const x = margin + (col * colWidth);
            const y = yPosition + (row * rowHeight);
            
            // Draw box
            doc.setDrawColor(229, 231, 235);
            doc.setFillColor(249, 250, 251);
            doc.rect(x, y, colWidth - 5, rowHeight - 5, 'FD');
            
            // Draw value
            doc.setFontSize(16);
            doc.setTextColor(37, 99, 235);
            doc.text(String(metric.value), x + 5, y + 12);
            
            // Draw label
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.text(metric.label, x + 5, y + 18);
        });
        
        yPosition += Math.ceil(metricsData.length / cols) * rowHeight + 10;

        // Division Performance Section
        if (divisions && divisions.length > 0) {
            checkPageBreak(60);
            
            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text('Division Performance', margin, yPosition);
            yPosition += 10;

            // Table Header
            doc.setFontSize(9);
            doc.setFillColor(249, 250, 251);
            doc.rect(margin, yPosition, maxWidth, 8, 'F');
            
            doc.setTextColor(75, 85, 99);
            doc.text('Division', margin + 2, yPosition + 6);
            doc.text('Leaders', margin + 60, yPosition + 6);
            doc.text('Score', margin + 85, yPosition + 6);
            doc.text('Ready', margin + 110, yPosition + 6);
            doc.text('HiPo', margin + 135, yPosition + 6);
            doc.text('At Risk', margin + 160, yPosition + 6);
            
            yPosition += 10;

            // Table Rows
            doc.setFontSize(8);
            divisions.forEach((div, idx) => {
                if (checkPageBreak(10)) {
                    // Redraw header on new page
                    doc.setFontSize(9);
                    doc.setFillColor(249, 250, 251);
                    doc.rect(margin, yPosition, maxWidth, 8, 'F');
                    doc.setTextColor(75, 85, 99);
                    doc.text('Division', margin + 2, yPosition + 6);
                    doc.text('Leaders', margin + 60, yPosition + 6);
                    doc.text('Score', margin + 85, yPosition + 6);
                    doc.text('Ready', margin + 110, yPosition + 6);
                    doc.text('HiPo', margin + 135, yPosition + 6);
                    doc.text('At Risk', margin + 160, yPosition + 6);
                    yPosition += 10;
                    doc.setFontSize(8);
                }
                
                doc.setTextColor(0, 0, 0);
                doc.text(div.name || 'Unknown', margin + 2, yPosition + 5);
                doc.text(String(div.leaders?.length || 0), margin + 60, yPosition + 5);
                doc.text(`${div.avgScore || 0}%`, margin + 85, yPosition + 5);
                doc.text(String(div.ready_now || 0), margin + 110, yPosition + 5);
                doc.text(String(div.high_potential || 0), margin + 135, yPosition + 5);
                doc.text(String(div.at_risk || 0), margin + 160, yPosition + 5);
                
                // Divider line
                doc.setDrawColor(229, 231, 235);
                doc.line(margin, yPosition + 7, pageWidth - margin, yPosition + 7);
                
                yPosition += 10;
            });
        }

        // Key Insights Section
        yPosition += 10;
        checkPageBreak(40);
        
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Strategic Insights', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        
        const insights = [
            `Organizational SI average of ${stats.avg_si_score}% indicates ${stats.avg_si_score >= 75 ? 'strong' : 'developing'} leadership capability.`,
            `Bench strength at ${stats.bench_strength}% with ${stats.ready_now} leaders ready for immediate promotion.`,
            `${stats.at_risk} leaders require attention and development interventions.`,
            `Pipeline strength of ${stats.pipeline_strength}% ${stats.pipeline_strength >= 20 ? 'meets' : 'falls below'} organizational resilience targets.`
        ];

        insights.forEach((insight, idx) => {
            checkPageBreak(15);
            doc.text(`• ${insight}`, margin + 5, yPosition);
            yPosition += 7;
        });

        yPosition += 10;
        checkPageBreak(30);

        // Recommendations Section
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Recommendations', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        
        const recommendations = [];
        
        if (stats.avg_si_score < 75) {
            recommendations.push('Deploy targeted SI development programs to raise organizational average to 75%+');
        }
        
        if (stats.at_risk > 0) {
            recommendations.push(`Implement intervention plans for ${stats.at_risk} at-risk leaders`);
        }
        
        if (stats.pipeline_strength < 20) {
            recommendations.push('Accelerate HiPo identification and development to build succession pipeline');
        }
        
        if (stats.bench_strength < 50) {
            recommendations.push('Expand leadership development initiatives to strengthen bench depth');
        }

        if (recommendations.length === 0) {
            recommendations.push('Continue monitoring leadership metrics and maintain current development programs');
        }

        recommendations.forEach((rec, idx) => {
            checkPageBreak(15);
            doc.text(`${idx + 1}. ${rec}`, margin + 5, yPosition);
            yPosition += 7;
        });

        // Footer on all pages
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text(`Page ${i} of ${pageCount}`, margin, pageHeight - 10);
            doc.text('Confidential - Enterprise Leadership Analytics', pageWidth - margin - 80, pageHeight - 10);
        }

        // Generate PDF
        const pdfBytes = doc.output('arraybuffer');

        return new Response(pdfBytes, {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="enterprise-analytics-${new Date().toISOString().split('T')[0]}.pdf"`
            }
        });

    } catch (error) {
        console.error('Error generating analytics PDF:', error);
        return Response.json({ 
            success: false, 
            error: error.message || 'Failed to generate PDF' 
        }, { status: 500 });
    }
});