import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

const TEST_CASES = [
  // User Role (49 base + 6 new features = 55 total)
  { test_case_id: "U_UC-1.1", role: "User", feature_area: "Dashboard & Navigation", description: "First Login & Welcome Dashboard: Log in for the first time and verify the personalized welcome message and initial dashboard layout.", expected_outcome: "Personalized welcome and proper dashboard display", priority: "P1" },
  { test_case_id: "U_UC-1.2", role: "User", feature_area: "Dashboard & Navigation", description: "Dashboard Data Accuracy: Verify that displayed data on the dashboard (e.g., goal counts, progress percentages, pending items) is accurate and reflects personal activity.", expected_outcome: "Data is accurate and reflects user activity", priority: "P1" },
  { test_case_id: "U_UC-1.3", role: "User", feature_area: "Dashboard & Navigation", description: "Navigation Between Main Sections: Navigate successfully between all primary sections of the application (e.g., Dashboard, Assessments, Learning & Development, Goals, Insights, Profile).", expected_outcome: "Smooth navigation without errors", priority: "P0" },
  { test_case_id: "U_UC-2.1", role: "User", feature_area: "Assessments", description: "View Available Assessments: Browse the 'Assessments' section to see a list of available self-assessments or assigned assessments.", expected_outcome: "List of assessments displayed correctly", priority: "P1" },
  { test_case_id: "U_UC-2.2", role: "User", feature_area: "Assessments", description: "Complete Leadership Index Assessment: Start and complete the Leadership Index assessment, answering all required questions.", expected_outcome: "Assessment completed successfully", priority: "P0" },
  { test_case_id: "U_UC-2.3", role: "User", feature_area: "Assessments", description: "View Assessment Results: Access and review personal assessment results, verifying the display of charts, scores, and AI-generated insights.", expected_outcome: "Results displayed with charts and insights", priority: "P0" },
  { test_case_id: "U_UC-2.4", role: "User", feature_area: "Assessments", description: "Export Assessment Results to PDF: Initiate the export of assessment results and verify that a PDF document is generated and downloaded correctly.", expected_outcome: "PDF generated and downloaded", priority: "P1" },
  { test_case_id: "U_UC-3.1", role: "User", feature_area: "Learning & Development", description: "Browse Learning Library with Filters: Navigate to the 'Learning Library' and use available filters (e.g., competency, leadership level, type) to narrow down learning resources.", expected_outcome: "Filters work correctly", priority: "P1" },
  { test_case_id: "U_UC-3.2", role: "User", feature_area: "Learning & Development", description: "View Learning Resource Details: Click on a learning resource to view its detailed description, objectives, duration, and access information.", expected_outcome: "Resource details displayed", priority: "P1" },
  { test_case_id: "U_UC-3.3", role: "User", feature_area: "Learning & Development", description: "Access and Manage Assigned Learning: Go to 'My Learning' to view and interact with learning resources assigned by a manager or the system, including marking completion.", expected_outcome: "Assigned learning visible and manageable", priority: "P0" },
  { test_case_id: "U_UC-3.4", role: "User", feature_area: "Learning & Development", description: "Explore Career Paths and Readiness Scores: Navigate to the 'Career Path Explorer' to view potential career paths and personal readiness scores for various roles.", expected_outcome: "Career paths and scores displayed", priority: "P2" },
  { test_case_id: "U_UC-3.5", role: "User", feature_area: "Learning & Development", description: "View Career Path Details: Select a career path to view its description, required competencies, recommended learning, and other requirements.", expected_outcome: "Career path details shown", priority: "P2" },
  { test_case_id: "U_UC-4.1", role: "User", feature_area: "Goals & Performance", description: "Create New Personal Goal: Create a new personal goal, providing a title, description, and other relevant details.", expected_outcome: "Goal created successfully", priority: "P0" },
  { test_case_id: "U_UC-4.2", role: "User", feature_area: "Goals & Performance", description: "Add Groups and Tasks to Goal: Within a personal goal, create new groups/sections and add individual tasks/milestones to them.", expected_outcome: "Groups and tasks added", priority: "P0" },
  { test_case_id: "U_UC-4.3", role: "User", feature_area: "Goals & Performance", description: "Edit Task Details: Modify the title, priority, status, due date, or progress of an existing task within a goal.", expected_outcome: "Task details updated", priority: "P0" },
  { test_case_id: "U_UC-4.4", role: "User", feature_area: "Goals & Performance", description: "Switch Between Goal Views: Change the display of a goal between different views (e.g., Table, Kanban, Calendar, Timeline, Unassigned) and verify layout correctness.", expected_outcome: "Views switch correctly", priority: "P1" },
  { test_case_id: "U_UC-4.5", role: "User", feature_area: "Goals & Performance", description: "Add Comments to Tasks: Add a new comment to a task and verify it appears in the task's comment history.", expected_outcome: "Comment added and visible", priority: "P1" },
  { test_case_id: "U_UC-4.6", role: "User", feature_area: "Goals & Performance", description: "Track Goal Progress: Update task statuses and progress, observing the automatic recalculation and display of overall goal progress.", expected_outcome: "Progress updates automatically", priority: "P0" },
  { test_case_id: "U_UC-4.7", role: "User", feature_area: "Goals & Performance", description: "View Goal Analytics Modal: Open the goal analytics modal to view detailed insights and metrics for a specific personal goal.", expected_outcome: "Analytics modal displays correctly", priority: "P2" },
  { test_case_id: "U_UC-4.8", role: "User", feature_area: "Goals & Performance", description: "Delete Task with Confirmation: Attempt to delete a task and confirm that a confirmation dialog appears before permanent deletion.", expected_outcome: "Confirmation dialog shown", priority: "P1" },
  { test_case_id: "U_UC-4.9", role: "User", feature_area: "Goals & Performance", description: "Delete Group with Confirmation: Attempt to delete a group of tasks and confirm that a confirmation dialog appears before permanent deletion.", expected_outcome: "Confirmation dialog shown", priority: "P1" },
  { test_case_id: "U_UC-5.1", role: "User", feature_area: "Journeys & Experiences", description: "View Enrolled Journeys and Progress: Access 'My Journeys' to see a list of enrolled learning journeys and their current progress.", expected_outcome: "Journeys list displayed", priority: "P1" },
  { test_case_id: "U_UC-5.2", role: "User", feature_area: "Journeys & Experiences", description: "Access Journey Module Details: Click into an enrolled journey to view its individual modules, learning resources, and completion requirements.", expected_outcome: "Journey details shown", priority: "P1" },
  { test_case_id: "U_UC-5.3", role: "User", feature_area: "Journeys & Experiences", description: "Complete Journey Modules/Resources: Interact with and complete individual modules or resources within a learning journey, verifying progress updates.", expected_outcome: "Progress updates on completion", priority: "P0" },
  { test_case_id: "U_UC-5.4", role: "User", feature_area: "Journeys & Experiences", description: "View Onboarding Plan (if assigned): If an onboarding plan is assigned, access it from the dashboard or relevant section to view its milestones and activities.", expected_outcome: "Onboarding plan accessible", priority: "P1" },
  { test_case_id: "U_UC-5.5", role: "User", feature_area: "Journeys & Experiences", description: "Complete Onboarding Milestones: Mark individual milestones within an assigned onboarding plan as complete and observe overall plan progress.", expected_outcome: "Milestones marked complete", priority: "P1" },
  { test_case_id: "U_UC-6.1", role: "User", feature_area: "AI Coach - Atreus", description: "Open Atreus with Personalized Greeting: Open the AI coach (Atreus) interface and verify a personalized welcome and initial prompt.", expected_outcome: "Personalized greeting shown", priority: "P1" },
  { test_case_id: "U_UC-6.2", role: "User", feature_area: "AI Coach - Atreus", description: "Ask General Development Question: Ask Atreus a general question about leadership development and receive a relevant and helpful response.", expected_outcome: "Relevant response received", priority: "P1" },
  { test_case_id: "U_UC-6.3", role: "User", feature_area: "AI Coach - Atreus", description: "Request Learning Recommendations: Request learning recommendations for a specific competency or development area and verify the suggestions are relevant.", expected_outcome: "Relevant recommendations provided", priority: "P1" },
  { test_case_id: "U_UC-6.4", role: "User", feature_area: "AI Coach - Atreus", description: "Create Goal via Atreus Assistance: Interact with Atreus to initiate and complete the creation of a new personal goal.", expected_outcome: "Goal created via Atreus", priority: "P2" },
  { test_case_id: "U_UC-6.5", role: "User", feature_area: "AI Coach - Atreus", description: "Conversation History Persistence: Close and reopen Atreus, verifying that previous conversation history is maintained.", expected_outcome: "History persists", priority: "P1" },
  { test_case_id: "U_UC-7.1", role: "User", feature_area: "Notifications", description: "View Notifications Bell: Observe the notification bell icon in the header, verifying that it displays an accurate unread count.", expected_outcome: "Unread count accurate", priority: "P1" },
  { test_case_id: "U_UC-7.2", role: "User", feature_area: "Notifications", description: "Mark Notification as Read: Click on an unread notification to open it, and verify that its status changes to 'read' and the unread count updates.", expected_outcome: "Notification marked read", priority: "P1" },
  { test_case_id: "U_UC-7.3", role: "User", feature_area: "Notifications", description: "View All Notifications Page: Navigate to the dedicated 'Notifications' page and apply filters to view specific types or statuses of notifications.", expected_outcome: "Filters work on notifications page", priority: "P2" },
  { test_case_id: "U_UC-8.1", role: "User", feature_area: "Profile & Settings", description: "View Complete Profile Page: Access the personal profile page to view all personal information, roles, and connected accounts.", expected_outcome: "Profile displayed correctly", priority: "P1" },
  { test_case_id: "U_UC-8.2", role: "User", feature_area: "Profile & Settings", description: "Update Profile Information: Edit and save changes to personal profile information (e.g., name, display picture, contact details).", expected_outcome: "Profile updated successfully", priority: "P1" },
  { test_case_id: "U_UC-8.3", role: "User", feature_area: "Profile & Settings", description: "Adjust Notification Preferences: Modify notification settings (e.g., email preferences, in-app alerts) and verify changes are saved.", expected_outcome: "Preferences saved", priority: "P2" },
  { test_case_id: "U_UC-8.4", role: "User", feature_area: "Profile & Settings", description: "Access Privacy Settings and Controls: Navigate to privacy settings to review data usage, consent, and data export options.", expected_outcome: "Privacy settings accessible", priority: "P2" },
  { test_case_id: "U_UC-9.1", role: "User", feature_area: "Insights", description: "View Personal Insights Dashboard: Access the personal insights dashboard to see an overview of personal performance, development trends, and key metrics.", expected_outcome: "Insights dashboard displayed", priority: "P1" },
  { test_case_id: "U_UC-9.2", role: "User", feature_area: "Insights", description: "Review AI-Generated Recommendations: Review AI-generated recommendations and action items presented on the insights dashboard.", expected_outcome: "Recommendations shown", priority: "P1" },
  { test_case_id: "U_UC-10.1", role: "User", feature_area: "Achievements & Gamification", description: "View Points Display in Header: Locate the points display in the application header and observe its value.", expected_outcome: "Points displayed in header", priority: "P1" },
  { test_case_id: "U_UC-10.2", role: "User", feature_area: "Achievements & Gamification", description: "Earn Points Through Actions: Perform an action (e.g., complete a goal, finish a learning resource) and verify that points are awarded and updated.", expected_outcome: "Points awarded correctly", priority: "P1" },
  { test_case_id: "U_UC-10.3", role: "User", feature_area: "Achievements & Gamification", description: "View Achievements Page: Navigate to the 'Achievements' page to view earned badges and awards.", expected_outcome: "Achievements page displayed", priority: "P2" },
  { test_case_id: "U_UC-11.1", role: "User", feature_area: "Mobile Responsiveness", description: "Dashboard on Mobile Viewport: Access the main dashboard on a mobile device or scaled-down browser viewport, verifying layout and readability.", expected_outcome: "Mobile layout works", priority: "P1" },
  { test_case_id: "U_UC-11.2", role: "User", feature_area: "Mobile Responsiveness", description: "Mobile Navigation Menu: Open and use the mobile navigation menu to access different sections of the application.", expected_outcome: "Mobile menu functional", priority: "P1" },
  { test_case_id: "U_UC-11.3", role: "User", feature_area: "Mobile Responsiveness", description: "Goal Creation/Management on Mobile: Create and manage a personal goal using the mobile interface, verifying usability of forms and interactions.", expected_outcome: "Mobile goal management works", priority: "P2" },
  { test_case_id: "U_UC-12.1", role: "User", feature_area: "Error Handling & Edge Cases", description: "Empty State Displays (New User): Log in as a new user with no existing data and verify that appropriate 'empty state' messages and prompts are displayed.", expected_outcome: "Empty states shown", priority: "P2" },
  { test_case_id: "U_UC-12.2", role: "User", feature_area: "Error Handling & Edge Cases", description: "Network Error Recovery: Simulate a network disconnection while performing an action and verify that the application handles the error gracefully and recovers upon reconnection.", expected_outcome: "Graceful error handling", priority: "P2" },
  { test_case_id: "U_UC-12.3", role: "User", feature_area: "Error Handling & Edge Cases", description: "Form Validation with Missing Fields: Attempt to submit a form (e.g., goal creation) with required fields left blank and verify that appropriate validation messages are displayed.", expected_outcome: "Validation messages shown", priority: "P1" },
  { test_case_id: "U_UC-13.1", role: "User", feature_area: "Search & Discovery", description: "Search Learning Resources: Use the search feature to find learning resources by keyword.", expected_outcome: "Search results accurate", priority: "P2" },
  { test_case_id: "U_UC-13.2", role: "User", feature_area: "Search & Discovery", description: "Filter by Competency: Filter learning resources and career paths by specific competencies.", expected_outcome: "Competency filter works", priority: "P2" },
  { test_case_id: "U_UC-13.3", role: "User", feature_area: "Bookmarking & Favorites", description: "Bookmark a Learning Resource: Mark a learning resource as a favorite or bookmark it for later access.", expected_outcome: "Resource bookmarked", priority: "P2" },
  { test_case_id: "U_UC-13.4", role: "User", feature_area: "Bookmarking & Favorites", description: "View Bookmarked Items: Access a list of all bookmarked or favorited learning resources.", expected_outcome: "Bookmarks displayed", priority: "P2" },
  { test_case_id: "U_UC-14.1", role: "User", feature_area: "Sharing & Collaboration", description: "Share Goal with Team Member: Share a personal goal with a colleague for feedback or collaboration.", expected_outcome: "Goal shared successfully", priority: "P2" },
  { test_case_id: "U_UC-14.2", role: "User", feature_area: "Sharing & Collaboration", description: "Invite Member to Goal: Invite a colleague to collaborate on a shared goal.", expected_outcome: "Invitation sent", priority: "P2" },

  // Team Leader Role (20 test cases)
  { test_case_id: "TL_UC-2.1", role: "Team Leader", feature_area: "Team Management Overview", description: "View Team Dashboard/Overview: Log in as a Team Leader, navigate to the Team Dashboard (or equivalent section for team overview).", expected_outcome: "Team dashboard accessible", priority: "P0" },
  { test_case_id: "TL_UC-2.2", role: "Team Leader", feature_area: "Team Management Overview", description: "Access Direct Report Profiles: From the Team Dashboard, click on a direct report's name or profile link.", expected_outcome: "Direct report profiles accessible", priority: "P1" },
  { test_case_id: "TL_UC-2.3", role: "Team Leader", feature_area: "Team Management Overview", description: "Search/Filter Team Members: Use search or filter options (if available) on the Team Dashboard or a team members list.", expected_outcome: "Search and filter functional", priority: "P2" },
  { test_case_id: "TL_UC-3.1", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Create Team Goal: Create a new goal and assign it to multiple team members or a team.", expected_outcome: "Team goal created", priority: "P0" },
  { test_case_id: "TL_UC-3.2", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Assign Personal Goal to Team Member: Create a personal goal (as a Team Leader) and then assign it to one or more direct reports.", expected_outcome: "Goal assigned to team member", priority: "P0" },
  { test_case_id: "TL_UC-3.3", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Add Tasks to Team Member's Goal: Navigate to a team member's goal and add a new task/milestone for them.", expected_outcome: "Task added to team member goal", priority: "P1" },
  { test_case_id: "TL_UC-3.4", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Edit Team Member's Task Details: Edit title, priority, status, or due date for a task assigned to a team member.", expected_outcome: "Task details edited", priority: "P1" },
  { test_case_id: "TL_UC-3.5", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Monitor Team Goal Progress: Review the progress of goals assigned to team members on the Team Dashboard or specific goal pages.", expected_outcome: "Team goal progress visible", priority: "P0" },
  { test_case_id: "TL_UC-3.6", role: "Team Leader", feature_area: "Goals & Performance (Team)", description: "Delete Team Member's Goal/Task: Delete a goal or task assigned to a team member.", expected_outcome: "Goal/task deleted", priority: "P2" },
  { test_case_id: "TL_UC-4.1", role: "Team Leader", feature_area: "Learning & Development (Team)", description: "Assign Learning Resource to Team Member: Browse the Learning Library and assign a specific learning resource to one or more direct reports.", expected_outcome: "Learning resource assigned", priority: "P0" },
  { test_case_id: "TL_UC-4.2", role: "Team Leader", feature_area: "Learning & Development (Team)", description: "Assign Learning Journey to Team Member: Assign a complete learning journey to one or more direct reports.", expected_outcome: "Journey assigned", priority: "P1" },
  { test_case_id: "TL_UC-4.3", role: "Team Leader", feature_area: "Learning & Development (Team)", description: "Monitor Team Learning Progress: On the Team Dashboard or a dedicated learning overview, review the completion status of assigned learning for team members.", expected_outcome: "Learning progress visible", priority: "P1" },
  { test_case_id: "TL_UC-5.1", role: "Team Leader", feature_area: "Assessments (Team)", description: "Assign Assessment to Team Member: Assign an available assessment (e.g., Leadership Index or custom assessment) to one or more direct reports.", expected_outcome: "Assessment assigned", priority: "P1" },
  { test_case_id: "TL_UC-5.2", role: "Team Leader", feature_area: "Assessments (Team)", description: "View Team Assessment Results: After team members complete assessments, review their individual results or aggregated team results (if available).", expected_outcome: "Team results visible", priority: "P1" },
  { test_case_id: "TL_UC-6.1", role: "Team Leader", feature_area: "Team Analytics and Insights", description: "Access Team Insights Dashboard: Navigate to the Insights section and select a 'Team View' or filter for their team.", expected_outcome: "Team insights accessible", priority: "P1" },
  { test_case_id: "TL_UC-6.2", role: "Team Leader", feature_area: "Team Analytics and Insights", description: "Review Team Performance Reports: Access available performance reports filtered for their team.", expected_outcome: "Team reports accessible", priority: "P2" },
  { test_case_id: "TL_UC-7.1", role: "Team Leader", feature_area: "Notifications", description: "Receive Team-Related Notifications: Simulate a team member completing a key task, missing a deadline, or submitting an assessment.", expected_outcome: "Notifications received", priority: "P2" },
  { test_case_id: "TL_UC-8.1", role: "Team Leader", feature_area: "Mobile Responsiveness (Team)", description: "Team Dashboard on Mobile: Access the Team Dashboard on a mobile device or responsive viewport.", expected_outcome: "Mobile team dashboard works", priority: "P2" },
  { test_case_id: "TL_UC-8.2", role: "Team Leader", feature_area: "Mobile Responsiveness (Team)", description: "Assign Goal/Learning on Mobile: Attempt to assign a goal or learning resource to a team member using a mobile device.", expected_outcome: "Mobile assignment works", priority: "P2" },
  { test_case_id: "TL_UC-9.1", role: "Team Leader", feature_area: "Error Handling & Edge Cases", description: "Attempt to Access Non-Direct Report Data: Attempt to view goals, learning, or assessment data for a user who is not a direct report.", expected_outcome: "Access denied appropriately", priority: "P2" },

  // Analyst Role (16 test cases)
  { test_case_id: "AN_UC-1.1", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "Access Organizational Dashboard: Log in as an Analyst and navigate to the Organizational Dashboard or equivalent section for high-level organizational insights.", expected_outcome: "Org dashboard accessible", priority: "P0" },
  { test_case_id: "AN_UC-1.2", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "View Aggregate Assessment Data: Access consolidated assessment results across all users, departments, or programs within the organization.", expected_outcome: "Aggregate data visible", priority: "P0" },
  { test_case_id: "AN_UC-1.3", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "Generate Custom Performance Reports: Utilize reporting tools to create custom reports based on various metrics (e.g., goal completion rates, learning engagement) with applied filters.", expected_outcome: "Custom reports generated", priority: "P1" },
  { test_case_id: "AN_UC-1.4", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "Access Learning Analytics: View comprehensive analytics related to learning resource usage, journey completion rates, and competency development across the organization.", expected_outcome: "Learning analytics accessible", priority: "P1" },
  { test_case_id: "AN_UC-1.5", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "Analyze Goal Performance Across Teams: Review and analyze goal performance data, comparing progress and outcomes across different teams or departments.", expected_outcome: "Goal analytics visible", priority: "P1" },
  { test_case_id: "AN_UC-1.6", role: "Analyst", feature_area: "Organizational Data & Reporting", description: "Export Organizational Data: Export filtered or aggregate data to common formats (e.g., CSV, PDF) for further analysis outside the platform.", expected_outcome: "Data exported successfully", priority: "P1" },
  { test_case_id: "AN_UC-2.1", role: "Analyst", feature_area: "Activity Monitoring & Insights", description: "Review User Activity Logs: Access and filter activity logs to monitor user engagement, common actions, and potential trends within the platform.", expected_outcome: "Activity logs accessible", priority: "P2" },
  { test_case_id: "AN_UC-2.2", role: "Analyst", feature_area: "Activity Monitoring & Insights", description: "Identify Organizational Trends: Analyze aggregated data to identify patterns, strengths, and areas for improvement in leadership development at an organizational level.", expected_outcome: "Trends identifiable", priority: "P1" },
  { test_case_id: "AN_UC-2.3", role: "Analyst", feature_area: "Activity Monitoring & Insights", description: "Access AI-Generated Organizational Insights: View AI-generated insights and recommendations that provide strategic guidance based on overall organizational data.", expected_outcome: "AI insights accessible", priority: "P1" },
  { test_case_id: "AN_UC-3.1", role: "Analyst", feature_area: "Data Integrity & Validation", description: "Verify Data Consistency: Perform checks to ensure data consistency across different reports and dashboards.", expected_outcome: "Data consistent", priority: "P2" },
  { test_case_id: "AN_UC-3.2", role: "Analyst", feature_area: "Data Integrity & Validation", description: "Validate Data Filters: Apply various filters (e.g., by department, role, date range) on different data sets and verify accurate filtering.", expected_outcome: "Filters accurate", priority: "P2" },
  { test_case_id: "AN_UC-4.1", role: "Analyst", feature_area: "Mobile Responsiveness", description: "Organizational Dashboard on Mobile: Access the Organizational Dashboard on a mobile device or scaled-down viewport.", expected_outcome: "Mobile org dashboard works", priority: "P2" },
  { test_case_id: "AN_UC-4.2", role: "Analyst", feature_area: "Mobile Responsiveness", description: "Review Reports on Mobile: Open and interact with generated reports or analytics visualizations on a mobile device.", expected_outcome: "Mobile reports work", priority: "P2" },
  { test_case_id: "AN_UC-5.1", role: "Analyst", feature_area: "Error Handling & Edge Cases", description: "Attempt to Modify Data: Attempt to modify any data (e.g., goals, assignments, user profiles) or system settings (should be denied).", expected_outcome: "Modification denied", priority: "P2" },
  { test_case_id: "AN_UC-5.2", role: "Analyst", feature_area: "Error Handling & Edge Cases", description: "Access Restricted Client/Partner Data: If multi-client/partner functionality is enabled, attempt to access data for a client or partner not assigned to the Analyst (should be denied).", expected_outcome: "Access denied", priority: "P2" },
  { test_case_id: "AN_UC-5.3", role: "Analyst", feature_area: "Error Handling & Edge Cases", description: "Report Generation with No Data: Generate a report for criteria where no data exists and verify appropriate empty state messages are displayed.", expected_outcome: "Empty state shown", priority: "P2" },

  // Program Administrator Role (22 test cases)
  { test_case_id: "PA_UC-1.1", role: "Program Administrator", feature_area: "Program & Cohort Management", description: "Create New Program/Cohort: Create a new leadership development program or cohort, defining its objectives, duration, and target audience.", expected_outcome: "Program/cohort created", priority: "P0" },
  { test_case_id: "PA_UC-1.2", role: "Program Administrator", feature_area: "Program & Cohort Management", description: "Enroll Participants in Cohort: Add or remove participants from an existing cohort.", expected_outcome: "Participants managed", priority: "P0" },
  { test_case_id: "PA_UC-1.3", role: "Program Administrator", feature_area: "Program & Cohort Management", description: "Manage Cohort Details: Edit program/cohort details such as start/end dates, descriptions, and assigned facilitators.", expected_outcome: "Details updated", priority: "P1" },
  { test_case_id: "PA_UC-1.4", role: "Program Administrator", feature_area: "Program & Cohort Management", description: "View Program Participants' Progress: Access an overview of all participants within a program or cohort, tracking their aggregated progress in learning journeys and assessments.", expected_outcome: "Progress visible", priority: "P1" },
  { test_case_id: "PA_UC-2.1", role: "Program Administrator", feature_area: "Learning Content Management", description: "Assign Learning Journeys to Cohorts: Assign pre-defined learning journeys to an entire cohort.", expected_outcome: "Journeys assigned to cohort", priority: "P0" },
  { test_case_id: "PA_UC-2.2", role: "Program Administrator", feature_area: "Learning Content Management", description: "Assign Individual Learning Resources: Assign specific learning resources to individual participants within a program.", expected_outcome: "Resources assigned", priority: "P1" },
  { test_case_id: "PA_UC-2.3", role: "Program Administrator", feature_area: "Learning Content Management", description: "Monitor Learning Journey Progress: Track the overall progress and completion rates of assigned learning journeys across the program.", expected_outcome: "Journey progress tracked", priority: "P1" },
  { test_case_id: "PA_UC-2.4", role: "Program Administrator", feature_area: "Learning Content Management", description: "Create/Edit Custom Learning Resources: (If permission allows) Create new or edit existing learning resources available within their programs.", expected_outcome: "Resources managed", priority: "P2" },
  { test_case_id: "PA_UC-3.1", role: "Program Administrator", feature_area: "Assessment & Goal Management", description: "Assign Custom Assessments: Assign custom assessments to participants or cohorts within their programs.", expected_outcome: "Assessments assigned", priority: "P1" },
  { test_case_id: "PA_UC-3.2", role: "Program Administrator", feature_area: "Assessment & Goal Management", description: "Review Program-Wide Assessment Results: Access aggregated assessment results and insights for all participants within a managed program.", expected_outcome: "Program results accessible", priority: "P1" },
  { test_case_id: "PA_UC-3.3", role: "Program Administrator", feature_area: "Assessment & Goal Management", description: "Oversee Participant Goals: View goals set by participants within their programs, and monitor their progress.", expected_outcome: "Participant goals visible", priority: "P1" },
  { test_case_id: "PA_UC-3.4", role: "Program Administrator", feature_area: "Assessment & Goal Management", description: "Trigger Goal Cascading: Initiate cascading of organizational goals to relevant managers within their programs.", expected_outcome: "Goal cascading works", priority: "P2" },
  { test_case_id: "PA_UC-4.1", role: "Program Administrator", feature_area: "Reporting & Analytics", description: "Generate Program Performance Reports: Generate detailed reports on program effectiveness, participant engagement, and development outcomes.", expected_outcome: "Reports generated", priority: "P1" },
  { test_case_id: "PA_UC-4.2", role: "Program Administrator", feature_area: "Reporting & Analytics", description: "Access Program Analytics Dashboard: Utilize a dedicated dashboard to visualize key performance indicators and trends for managed programs.", expected_outcome: "Analytics dashboard accessible", priority: "P1" },
  { test_case_id: "PA_UC-4.3", role: "Program Administrator", feature_area: "Reporting & Analytics", description: "Identify Underperforming Participants/Cohorts: Use analytics to identify participants or cohorts that may be struggling and require intervention.", expected_outcome: "Underperformers identified", priority: "P2" },
  { test_case_id: "PA_UC-5.1", role: "Program Administrator", feature_area: "Notifications", description: "Send Program-Wide Announcements: Send notifications or announcements to all participants within a specific program or cohort.", expected_outcome: "Announcements sent", priority: "P2" },
  { test_case_id: "PA_UC-5.2", role: "Program Administrator", feature_area: "Notifications", description: "Receive Program-Related Alerts: Receive alerts for critical program events (e.g., low completion rates, overdue assignments for multiple participants).", expected_outcome: "Alerts received", priority: "P2" },
  { test_case_id: "PA_UC-6.1", role: "Program Administrator", feature_area: "Mobile Responsiveness", description: "Program/Cohort Management on Mobile: Manage program or cohort details using a mobile device or scaled-down viewport.", expected_outcome: "Mobile program management works", priority: "P2" },
  { test_case_id: "PA_UC-6.2", role: "Program Administrator", feature_area: "Mobile Responsiveness", description: "Review Program Reports on Mobile: Access and review generated program reports and analytics on a mobile device.", expected_outcome: "Mobile reports accessible", priority: "P2" },
  { test_case_id: "PA_UC-7.1", role: "Program Administrator", feature_area: "Error Handling & Edge Cases", description: "Attempt to Manage Programs Outside Scope: Attempt to access or modify programs or cohorts not assigned to their administration (should be denied).", expected_outcome: "Access denied", priority: "P2" },
  { test_case_id: "PA_UC-7.2", role: "Program Administrator", feature_area: "Error Handling & Edge Cases", description: "Attempt to Edit System-Level Content: Attempt to modify platform-level learning resources or assessment templates not created by them (should be denied).", expected_outcome: "Edit denied", priority: "P2" },
  { test_case_id: "PA_UC-7.3", role: "Program Administrator", feature_area: "Error Handling & Edge Cases", description: "Program with No Participants: Verify behavior when managing a newly created program or cohort with no participants enrolled.", expected_outcome: "Empty state handled", priority: "P2" },

  // HR Administrator Role (22 test cases)
  { test_case_id: "HR_UC-1.1", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "Onboard New User: Invite a new user to the platform, assign their initial role (e.g., User Level 1), and verify their successful registration.", expected_outcome: "User onboarded successfully", priority: "P0" },
  { test_case_id: "HR_UC-1.2", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "Update User Role: Change an existing user's role (e.g., promote a User Level 1 to Team Leader) and verify that their access and permissions update accordingly.", expected_outcome: "Role updated with permissions", priority: "P0" },
  { test_case_id: "HR_UC-1.3", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "Deactivate/Archive User Account: Deactivate or archive a user's account and verify that their access is revoked while their data is retained.", expected_outcome: "Account deactivated", priority: "P1" },
  { test_case_id: "HR_UC-1.4", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "Reactivate User Account: Reactivate a previously deactivated user account and verify full access restoration.", expected_outcome: "Account reactivated", priority: "P2" },
  { test_case_id: "HR_UC-1.5", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "View All User Profiles: Access a comprehensive list of all users in the organization, including their roles and key attributes.", expected_outcome: "User list displayed", priority: "P1" },
  { test_case_id: "HR_UC-1.6", role: "HR Administrator", feature_area: "User Management & Lifecycle", description: "Bulk Import Users: Import multiple user accounts using a CSV or similar file, verifying correct creation and role assignment.", expected_outcome: "Bulk import successful", priority: "P1" },
  { test_case_id: "HR_UC-2.1", role: "HR Administrator", feature_area: "Organizational & Client Management", description: "Manage Organizational Structure: Create, edit, or delete departments, divisions, or reporting lines within the organizational structure.", expected_outcome: "Structure managed", priority: "P1" },
  { test_case_id: "HR_UC-2.2", role: "HR Administrator", feature_area: "Organizational & Client Management", description: "Configure Client-Specific Settings: (If multi-client environment) Configure settings, features, or branding specific to their client organization.", expected_outcome: "Settings configured", priority: "P2" },
  { test_case_id: "HR_UC-2.3", role: "HR Administrator", feature_area: "Organizational & Client Management", description: "Manage Role Definitions: Create or modify custom roles and their associated permissions within the organization.", expected_outcome: "Roles managed", priority: "P2" },
  { test_case_id: "HR_UC-3.1", role: "HR Administrator", feature_area: "Global Program & Content Assignment", description: "Assign Programs/Cohorts Globally: Assign a learning program or cohort to multiple teams, departments, or the entire organization.", expected_outcome: "Programs assigned globally", priority: "P1" },
  { test_case_id: "HR_UC-3.2", role: "HR Administrator", feature_area: "Global Program & Content Assignment", description: "Bulk Assign Learning Resources: Assign specific learning resources or journeys to a large group of users or an entire department.", expected_outcome: "Bulk assignment successful", priority: "P1" },
  { test_case_id: "HR_UC-3.3", role: "HR Administrator", feature_area: "Global Program & Content Assignment", description: "Global Assessment Assignment: Assign a specific assessment to all relevant users within the organization.", expected_outcome: "Assessment assigned globally", priority: "P1" },
  { test_case_id: "HR_UC-4.1", role: "HR Administrator", feature_area: "Reporting, Analytics & Compliance", description: "Access Global Performance Analytics: View aggregated performance and development analytics across the entire organization.", expected_outcome: "Global analytics accessible", priority: "P1" },
  { test_case_id: "HR_UC-4.2", role: "HR Administrator", feature_area: "Reporting, Analytics & Compliance", description: "Generate Compliance Reports: Generate reports related to user training completion, assessment participation, or other compliance metrics.", expected_outcome: "Compliance reports generated", priority: "P1" },
  { test_case_id: "HR_UC-4.3", role: "HR Administrator", feature_area: "Reporting, Analytics & Compliance", description: "Monitor Platform Usage Trends: Analyze overall platform engagement, feature adoption, and user activity across the organization.", expected_outcome: "Usage trends visible", priority: "P2" },
  { test_case_id: "HR_UC-5.1", role: "HR Administrator", feature_area: "Platform Administration & Branding", description: "Manage Branding Configuration: Upload custom logos, set primary/secondary colors, and configure other branding elements for the platform.", expected_outcome: "Branding configured", priority: "P2" },
  { test_case_id: "HR_UC-5.2", role: "HR Administrator", feature_area: "Platform Administration & Branding", description: "Customize Platform Terminology: Adjust terminology used within the platform to align with organizational language.", expected_outcome: "Terminology customized", priority: "P2" },
  { test_case_id: "HR_UC-5.3", role: "HR Administrator", feature_area: "Platform Administration & Branding", description: "Set System-Wide Notifications: Configure and schedule system-wide notifications or announcements for all users.", expected_outcome: "Notifications configured", priority: "P2" },
  { test_case_id: "HR_UC-5.4", role: "HR Administrator", feature_area: "Platform Administration & Branding", description: "Audit Trail Review: Access and review audit logs for administrative actions and system changes.", expected_outcome: "Audit logs accessible", priority: "P2" },
  { test_case_id: "HR_UC-6.1", role: "HR Administrator", feature_area: "Error Handling & Security", description: "Attempt Unauthorized System Changes: Attempt to access or modify global platform settings or data outside their client scope (should be denied).", expected_outcome: "Access denied", priority: "P2" },
  { test_case_id: "HR_UC-6.2", role: "HR Administrator", feature_area: "Error Handling & Security", description: "Data Privacy Compliance: Verify that user data access and modifications adhere to established privacy rules and regulations (e.g., GDPR, CCPA).", expected_outcome: "Compliance verified", priority: "P2" },
  { test_case_id: "HR_UC-6.3", role: "HR Administrator", feature_area: "Error Handling & Security", description: "Bulk Action Error Handling: Perform a bulk user import with errors in the data file and verify robust error reporting and partial import handling.", expected_outcome: "Errors handled gracefully", priority: "P2" },

  // Super Administrator Role (18 test cases)
  { test_case_id: "SA_UC-1.1", role: "Super Administrator", feature_area: "Platform & Client Management", description: "Global Client Oversight: Access and manage all client organizations within the platform, including their settings, plans, and user bases.", expected_outcome: "All clients accessible", priority: "P1" },
  { test_case_id: "SA_UC-1.2", role: "Super Administrator", feature_area: "Platform & Client Management", description: "Impersonate Any User: Utilize the impersonation feature to temporarily assume the identity of any user (including other admins) for troubleshooting or support purposes.", expected_outcome: "Impersonation works", priority: "P1" },
  { test_case_id: "SA_UC-1.3", role: "Super Administrator", feature_area: "Platform & Client Management", description: "Manage Platform-Wide Defaults: Configure and update default settings for entities such as competencies, roles, and learning resources that apply across all clients.", expected_outcome: "Defaults managed", priority: "P2" },
  { test_case_id: "SA_UC-1.4", role: "Super Administrator", feature_area: "Platform & Client Management", description: "Create/Delete Client Organizations: Create new client organizations or permanently delete existing ones from the platform.", expected_outcome: "Clients created/deleted", priority: "P1" },
  { test_case_id: "SA_UC-1.5", role: "Super Administrator", feature_area: "Platform & Client Management", description: "Monitor Platform Health Metrics: Access dashboards that display critical platform performance metrics, resource utilization, and overall system health.", expected_outcome: "Health metrics visible", priority: "P2" },
  { test_case_id: "SA_UC-2.1", role: "Super Administrator", feature_area: "Advanced User & Role Administration", description: "Promote/Demote Administrative Roles: Assign or revoke HR Administrator and Program Administrator roles to users across any client.", expected_outcome: "Roles promoted/demoted", priority: "P1" },
  { test_case_id: "SA_UC-2.2", role: "Super Administrator", feature_area: "Advanced User & Role Administration", description: "Global User Search: Search for and manage any user across all client organizations, including viewing their profiles and activity.", expected_outcome: "Global search works", priority: "P1" },
  { test_case_id: "SA_UC-2.3", role: "Super Administrator", feature_area: "Advanced User & Role Administration", description: "Override User Permissions: Temporarily or permanently adjust specific user permissions, even those outside standard role definitions.", expected_outcome: "Permissions overridden", priority: "P2" },
  { test_case_id: "SA_UC-3.1", role: "Super Administrator", feature_area: "System Configuration & Integrations", description: "Manage Backend Functions: Deploy, update, or remove backend functions that power various platform features.", expected_outcome: "Functions managed", priority: "P2" },
  { test_case_id: "SA_UC-3.2", role: "Super Administrator", feature_area: "System Configuration & Integrations", description: "Configure Global Integrations: Set up and manage platform-wide integrations with external services (e.g., payment gateways, communication tools).", expected_outcome: "Integrations configured", priority: "P2" },
  { test_case_id: "SA_UC-3.3", role: "Super Administrator", feature_area: "System Configuration & Integrations", description: "Access & Manage System Secrets: View, add, update, or remove sensitive system secrets (e.g., API keys, webhooks) that are used by backend functions and integrations.", expected_outcome: "Secrets managed", priority: "P2" },
  { test_case_id: "SA_UC-3.4", role: "Super Administrator", feature_area: "System Configuration & Integrations", description: "Manage Automated Workflows: Oversee and configure system-level automated workflows and scheduled tasks impacting all clients.", expected_outcome: "Workflows managed", priority: "P2" },
  { test_case_id: "SA_UC-4.1", role: "Super Administrator", feature_area: "Auditing, Security & Compliance", description: "Comprehensive Audit Trail Review: Access and filter a complete audit log of all administrative actions and significant user activities across the entire platform.", expected_outcome: "Audit trail accessible", priority: "P2" },
  { test_case_id: "SA_UC-4.2", role: "Super Administrator", feature_area: "Auditing, Security & Compliance", description: "Data Access & Retention Policies: Define and enforce data access policies and data retention schedules at a global level.", expected_outcome: "Policies configured", priority: "P2" },
  { test_case_id: "SA_UC-4.3", role: "Super Administrator", feature_area: "Auditing, Security & Compliance", description: "Monitor Security Incidents: Access and respond to security alerts and incident logs to ensure platform integrity.", expected_outcome: "Security monitoring works", priority: "P2" },
  { test_case_id: "SA_UC-5.1", role: "Super Administrator", feature_area: "Error Handling & Edge Cases", description: "Attempt Invalid System Configuration: Attempt to save invalid or conflicting system-wide configurations and verify appropriate error handling and prevention.", expected_outcome: "Invalid config prevented", priority: "P2" },
  { test_case_id: "SA_UC-5.2", role: "Super Administrator", feature_area: "Error Handling & Edge Cases", description: "Global Data Deletion: Perform a bulk data deletion or client deletion and verify all associated data is correctly purged while maintaining data integrity for other clients.", expected_outcome: "Data deletion works correctly", priority: "P2" },
  { test_case_id: "SA_UC-5.3", role: "Super Administrator", feature_area: "Error Handling & Edge Cases", description: "Concurrent Admin Modifications: Simulate multiple Super Administrators making concurrent modifications to global settings and verify proper locking and conflict resolution.", expected_outcome: "Conflicts resolved", priority: "P2" },

  // Partner Business Administrator Role (16 test cases)
  { test_case_id: "PB_UC-1.1", role: "Partner Business Administrator", feature_area: "Client Management & Onboarding", description: "Create New Client Organization: Onboard a new client organization, linking it to the partner entity.", expected_outcome: "Client created", priority: "P1" },
  { test_case_id: "PB_UC-1.2", role: "Partner Business Administrator", feature_area: "Client Management & Onboarding", description: "Manage Client Subscription & Features: Adjust subscription plans, license counts, and feature access for managed client organizations.", expected_outcome: "Subscription managed", priority: "P1" },
  { test_case_id: "PB_UC-1.3", role: "Partner Business Administrator", feature_area: "Client Management & Onboarding", description: "Access Client-Specific Settings: Navigate and manage settings for individual client organizations, including their specific configurations and administrative roles.", expected_outcome: "Client settings accessible", priority: "P1" },
  { test_case_id: "PB_UC-1.4", role: "Partner Business Administrator", feature_area: "Client Management & Onboarding", description: "View All Managed Clients: Access a dashboard or list showing all client organizations under the partner's management.", expected_outcome: "Client list displayed", priority: "P1" },
  { test_case_id: "PB_UC-2.1", role: "Partner Business Administrator", feature_area: "Partner-Level Branding & Customization", description: "Apply Partner Branding to Clients: Configure and apply partner-specific branding (logos, colors, platform names) that cascade to all managed client organizations.", expected_outcome: "Branding applied", priority: "P2" },
  { test_case_id: "PB_UC-2.2", role: "Partner Business Administrator", feature_area: "Partner-Level Branding & Customization", description: "Create Partner-Specific Default Content: Establish default competencies, roles, or learning paths that are automatically available to new or existing managed clients.", expected_outcome: "Defaults created", priority: "P2" },
  { test_case_id: "PB_UC-3.1", role: "Partner Business Administrator", feature_area: "Billing & Commission Management", description: "View Partner Commission Reports: Access reports detailing commissions earned from managed client subscriptions and usage.", expected_outcome: "Commission reports visible", priority: "P1" },
  { test_case_id: "PB_UC-3.2", role: "Partner Business Administrator", feature_area: "Billing & Commission Management", description: "Manage Client Billing Information: Update billing details and view invoicing history for managed client organizations.", expected_outcome: "Billing info managed", priority: "P1" },
  { test_case_id: "PB_UC-3.3", role: "Partner Business Administrator", feature_area: "Billing & Commission Management", description: "Approve Commission Payouts: Review and approve commission payouts from the platform (if applicable to the business model).", expected_outcome: "Payouts approved", priority: "P2" },
  { test_case_id: "PB_UC-4.1", role: "Partner Business Administrator", feature_area: "Aggregate Reporting & Analytics", description: "Access Aggregate Analytics Across Clients: View consolidated performance, learning, and engagement analytics across all managed client organizations.", expected_outcome: "Aggregate analytics visible", priority: "P1" },
  { test_case_id: "PB_UC-4.2", role: "Partner Business Administrator", feature_area: "Aggregate Reporting & Analytics", description: "Generate Cross-Client Reports: Create reports that compare or combine data from multiple managed client organizations.", expected_outcome: "Cross-client reports generated", priority: "P2" },
  { test_case_id: "PB_UC-5.1", role: "Partner Business Administrator", feature_area: "User Administration", description: "Administer Users in Managed Clients: Create, update, or deactivate users within any managed client organization.", expected_outcome: "User administration works", priority: "P1" },
  { test_case_id: "PB_UC-5.2", role: "Partner Business Administrator", feature_area: "User Administration", description: "Promote/Demote Client Administrators: Assign or revoke HR Administrator or Program Administrator roles within a managed client organization.", expected_outcome: "Admin roles managed", priority: "P2" },
  { test_case_id: "PB_UC-6.1", role: "Partner Business Administrator", feature_area: "Error Handling & Security", description: "Attempt to Access Unmanaged Clients: Attempt to view or manage client organizations not associated with their partner account (should be denied).", expected_outcome: "Access denied", priority: "P2" },
  { test_case_id: "PB_UC-6.2", role: "Partner Business Administrator", feature_area: "Error Handling & Security", description: "Data Isolation Verification: Confirm that data from one managed client cannot be accidentally viewed or modified by another managed client.", expected_outcome: "Data isolated", priority: "P2" },
  { test_case_id: "PB_UC-6.3", role: "Partner Business Administrator", feature_area: "Error Handling & Security", description: "Billing Discrepancy Reconciliation: Verify processes for identifying and resolving discrepancies in client billing or partner commission reports.", expected_outcome: "Discrepancies handled", priority: "P2" },

  // Platform Administrator Role (21 test cases)
  { test_case_id: "PL_UC-1.1", role: "Platform Administrator", feature_area: "Global Platform Configuration", description: "Manage Global Entity Schemas: Modify or extend core entity schemas (e.g., User, Goal, Competency) directly at the platform level, ensuring changes propagate correctly without breaking existing data or functionality.", expected_outcome: "Schemas modified safely", priority: "P2" },
  { test_case_id: "PL_UC-1.2", role: "Platform Administrator", feature_area: "Global Platform Configuration", description: "Configure System-Wide Defaults: Set and update default values and configurations for any entity or feature that new clients/organizations inherit upon creation.", expected_outcome: "Defaults configured", priority: "P2" },
  { test_case_id: "PL_UC-1.3", role: "Platform Administrator", feature_area: "Global Platform Configuration", description: "Manage Platform Branding/Theming: Define the core platform's branding, default visual themes, and overall user experience that clients can then customize or override.", expected_outcome: "Platform branding managed", priority: "P2" },
  { test_case_id: "PL_UC-1.4", role: "Platform Administrator", feature_area: "Global Platform Configuration", description: "Manage Subscription Plans & Pricing: Define, modify, and activate different subscription tiers, pricing models, and feature sets for clients and partners.", expected_outcome: "Pricing managed", priority: "P1" },
  { test_case_id: "PL_UC-1.5", role: "Platform Administrator", feature_area: "Global Platform Configuration", description: "Control Feature Flags: Enable or disable new features or modules at a global level for phased rollouts or A/B testing across the entire platform.", expected_outcome: "Feature flags controlled", priority: "P1" },
  { test_case_id: "PL_UC-2.1", role: "Platform Administrator", feature_area: "Infrastructure & Backend Management", description: "Deploy & Manage Backend Functions: Deploy, update, or roll back all backend functions, ensuring proper version control and error handling.", expected_outcome: "Functions deployed", priority: "P1" },
  { test_case_id: "PL_UC-2.2", role: "Platform Administrator", feature_area: "Infrastructure & Backend Management", description: "Monitor System Performance & Logs: Access comprehensive system logs, performance metrics, and error reporting for the entire platform to diagnose and resolve infrastructure-level issues.", expected_outcome: "Logs and metrics accessible", priority: "P1" },
  { test_case_id: "PL_UC-2.3", role: "Platform Administrator", feature_area: "Infrastructure & Backend Management", description: "Manage Database Access & Permissions: Configure and audit database access rules, ensure data security, and manage data migration tasks across the platform.", expected_outcome: "Database access managed", priority: "P2" },
  { test_case_id: "PL_UC-2.4", role: "Platform Administrator", feature_area: "Infrastructure & Backend Management", description: "Configure Webhooks & External Services: Set up and manage system-wide webhooks, API endpoints, and connections to critical external services.", expected_outcome: "Webhooks configured", priority: "P1" },
  { test_case_id: "PL_UC-3.1", role: "Platform Administrator", feature_area: "User & Role Framework Management", description: "Define Core Role Permissions: Directly modify the base permission sets for all default roles (e.g., User Level 1, Team Leader, Analyst) that are then inherited by clients.", expected_outcome: "Permissions defined", priority: "P1" },
  { test_case_id: "PL_UC-3.2", role: "Platform Administrator", feature_area: "User & Role Framework Management", description: "Manage Add-on Permission Modules: Create, update, or disable entire add-on modules that grant specific sets of permissions (e.g., 'Team Leader Add-on,' 'Analyst Add-on').", expected_outcome: "Add-ons managed", priority: "P2" },
  { test_case_id: "PL_UC-3.3", role: "Platform Administrator", feature_area: "User & Role Framework Management", description: "Global User Impersonation: Impersonate any user, including Super Administrators and Partner Business Administrators, to troubleshoot complex, multi-level issues.", expected_outcome: "Global impersonation works", priority: "P1" },
  { test_case_id: "PL_UC-4.1", role: "Platform Administrator", feature_area: "Billing & Financial Operations", description: "Oversee Billing System Integrations: Verify the health and functionality of payment gateway integrations (e.g., Stripe) and ensure accurate transaction processing.", expected_outcome: "Billing health verified", priority: "P1" },
  { test_case_id: "PL_UC-4.2", role: "Platform Administrator", feature_area: "Billing & Financial Operations", description: "Audit Client/Partner Billing: Review and reconcile billing data and commission calculations for all clients and partners to ensure financial accuracy.", expected_outcome: "Billing audited", priority: "P2" },
  { test_case_id: "PL_UC-4.3", role: "Platform Administrator", feature_area: "Billing & Financial Operations", description: "Issue Refunds/Adjustments: Process refunds or manual adjustments to client subscriptions or invoices.", expected_outcome: "Refunds processed", priority: "P2" },
  { test_case_id: "PL_UC-5.1", role: "Platform Administrator", feature_area: "Platform Governance & Compliance", description: "Enforce Global Data Privacy Regulations: Ensure the platform's compliance with overarching data privacy regulations (e.g., GDPR, CCPA) across all client data.", expected_outcome: "Privacy compliance enforced", priority: "P1" },
  { test_case_id: "PL_UC-5.2", role: "Platform Administrator", feature_area: "Platform Governance & Compliance", description: "Conduct Security Audits: Initiate and manage platform-wide security audits and penetration testing.", expected_outcome: "Security audits conducted", priority: "P2" },
  { test_case_id: "PL_UC-5.3", role: "Platform Administrator", feature_area: "Platform Governance & Compliance", description: "Manage Incident Response: Lead and coordinate the response to critical security incidents or platform-wide outages.", expected_outcome: "Incident response managed", priority: "P1" },
  { test_case_id: "PL_UC-6.1", role: "Platform Administrator", feature_area: "Error Handling & Disaster Recovery", description: "Simulate System Component Failure: Test the platform's resilience and error handling by simulating failures in core services (e.g., database, authentication service).", expected_outcome: "Failures handled", priority: "P2" },
  { test_case_id: "PL_UC-6.2", role: "Platform Administrator", feature_area: "Error Handling & Disaster Recovery", description: "Execute Disaster Recovery Procedures: Perform full data backups and simulated restorations to ensure business continuity.", expected_outcome: "Recovery successful", priority: "P2" },
  { test_case_id: "PL_UC-6.3", role: "Platform Administrator", feature_area: "Error Handling & Disaster Recovery", description: "Resolve Cross-Client Data Conflicts: Identify and resolve rare data conflicts or inconsistencies that might arise across different client instances.", expected_outcome: "Conflicts resolved", priority: "P2" }
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.app_role !== 'Platform Admin') {
      return Response.json({ error: 'Unauthorized - Platform Admin only' }, { status: 403 });
    }

    // STEP 1: Delete ALL existing test cases
    console.log('Fetching all existing UAT test cases for deletion...');
    const existingTestCases = await base44.asServiceRole.entities.UATTestCase.filter({});
    
    if (existingTestCases && existingTestCases.length > 0) {
      console.log(`Found ${existingTestCases.length} existing test cases. Deleting all...`);
      
      // Delete in batches for performance
      const batchSize = 50;
      for (let i = 0; i < existingTestCases.length; i += batchSize) {
        const batch = existingTestCases.slice(i, i + batchSize);
        await Promise.all(batch.map(tc => base44.asServiceRole.entities.UATTestCase.delete(tc.id)));
        console.log(`Deleted batch ${Math.floor(i / batchSize) + 1} of ${Math.ceil(existingTestCases.length / batchSize)}`);
      }
      
      console.log('All existing test cases deleted.');
    } else {
      console.log('No existing test cases found.');
    }

    // STEP 2: Create fresh test cases from PDF
    console.log('Creating fresh test cases from PDF...');
    const testCasesWithDefaults = TEST_CASES.map(tc => ({
      test_case_id: tc.test_case_id,
      role: tc.role,
      feature_area: tc.feature_area,
      description: tc.description,
      expected_outcome: tc.expected_outcome,
      priority: tc.priority || 'P2',
      test_runs: [],
      overall_risk_score: 0,
      guided_steps: [] // Ready for guided testing integration
    }));

    await base44.asServiceRole.entities.UATTestCase.bulkCreate(testCasesWithDefaults);

    return Response.json({
      success: true,
      message: `Successfully cleaned and seeded ${TEST_CASES.length} UAT test cases from PDF`,
      deleted: existingTestCases?.length || 0,
      created: TEST_CASES.length,
      breakdown: {
        user: TEST_CASES.filter(t => t.role === 'User').length,
        team_leader: TEST_CASES.filter(t => t.role === 'Team Leader').length,
        analyst: TEST_CASES.filter(t => t.role === 'Analyst').length,
        program_admin: TEST_CASES.filter(t => t.role === 'Program Administrator').length,
        hr_admin: TEST_CASES.filter(t => t.role === 'HR Administrator').length,
        super_admin: TEST_CASES.filter(t => t.role === 'Super Administrator').length,
        partner_admin: TEST_CASES.filter(t => t.role === 'Partner Business Administrator').length,
        platform_admin: TEST_CASES.filter(t => t.role === 'Platform Administrator').length
      }
    });

  } catch (error) {
    console.error('Error seeding UAT test cases from PDF:', error);
    return Response.json({ 
      error: error?.message || 'Unknown error occurred',
      success: false 
    }, { status: 500 });
  }
});