import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { request_id } = await req.json();

    if (!request_id) {
      return Response.json({ error: 'request_id is required' }, { status: 400 });
    }

    // Fetch the request
    const requests = await base44.asServiceRole.entities.DevelopmentRequest.filter({ 
      id: request_id 
    });
    
    if (requests.length === 0) {
      return Response.json({ error: 'Request not found' }, { status: 404 });
    }

    const request = requests[0];

    // Build comprehensive context for AI analysis
    const context = `
Development Request Decision Packet

REQUEST DETAILS:
- Title: ${request.title}
- Type: ${request.request_type}
- Priority: ${request.priority}
- Status: ${request.status}
- Requested by: ${request.requested_by_email}
- Assigned to: ${request.assigned_to_email || 'Unassigned'}

DESCRIPTION:
${request.description}

SCOPE & IMPACT:
- Estimated Effort: ${request.estimated_effort_hours || 'Not estimated'} hours
- Budget Required: $${request.budget_amount?.toLocaleString() || 'Not specified'}
- Target Audience Size: ${request.audience_size || 'Not specified'} users
- Invitation Only: ${request.is_invitation_only ? 'Yes' : 'No'}
- Due Date: ${request.due_date || 'Not set'}

RISK ASSESSMENT:
${request.risk_flags && request.risk_flags.length > 0 
  ? request.risk_flags.map(flag => `- ${flag.replace(/_/g, ' ').toUpperCase()}`).join('\n')
  : '- No risk flags identified'}

APPROVAL STATUS:
- Requires Approval: ${request.requires_approval ? 'YES' : 'NO'}
- Current Approval Status: ${request.approval_status}

INITIAL NOTES:
${request.initial_notes || 'None provided'}
    `.trim();

    // Generate AI analysis
    const analysis = await base44.integrations.Core.InvokeLLM({
      prompt: `You are a strategic advisor for L&D and Talent Management initiatives. Analyze this development request and provide a comprehensive decision packet for leadership approval.

${context}

Please provide a structured analysis including:

1. **Executive Summary** (2-3 sentences highlighting key decision points)

2. **Business Impact Analysis**
   - Strategic alignment
   - Expected benefits and outcomes
   - Potential risks if NOT approved

3. **Resource Requirements**
   - Time investment
   - Budget justification
   - Personnel needs

4. **Risk Mitigation**
   - Identified risks and mitigation strategies
   - Compliance considerations
   - Quality assurance approach

5. **Alternative Options** (if any less costly/time-intensive alternatives exist)

6. **Recommendation** (Approve, Approve with conditions, Reject, or Request more information)

7. **Success Metrics** (How will we measure success of this initiative?)

Be data-driven, concise, and focus on business value. Format in clear markdown.`,
      add_context_from_internet: false
    });

    // Store the decision packet in the request notes
    const decisionPacket = `## AI-Generated Decision Packet
Generated on: ${new Date().toISOString()}

${analysis}

---
*This analysis was generated by AI and should be reviewed by leadership.*`;

    // Update request with the decision packet
    await base44.asServiceRole.entities.DevelopmentRequest.update(request_id, {
      initial_notes: (request.initial_notes || '') + '\n\n' + decisionPacket
    });

    return Response.json({
      success: true,
      decision_packet: decisionPacket,
      analysis: analysis
    });

  } catch (error) {
    console.error('Decision packet generation error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});