import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const COURSES = [
  // Situational Intelligence
  { title: "Unconscious Bias", provider: "LinkedIn Learning", author: "Stacey Gordon", url: "https://www.linkedin.com/learning/unconscious-bias", competencies: ["Situational Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "57 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Developing Your Emotional Intelligence", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/developing-your-emotional-intelligence", competencies: ["Situational Intelligence"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Situational Leadership Foundations", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/situational-leadership-foundations", competencies: ["Situational Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 15m", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  // Decision Making
  { title: "Making Data-Driven Decisions", provider: "LinkedIn Learning", author: "Barton Poulson", url: "https://www.linkedin.com/learning/making-data-driven-decisions", competencies: ["Decision Making"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 22m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Critical Thinking", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/critical-thinking", competencies: ["Decision Making"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "59 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Decision-Making Under Pressure", provider: "LinkedIn Learning", author: "Dorie Clark", url: "https://www.linkedin.com/learning/decision-making-under-pressure", competencies: ["Decision Making"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "advanced", type: "course", duration_string: "45 min", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Communication
  { title: "Communication Foundations", provider: "LinkedIn Learning", author: "Brenda Bailey-Hughes", url: "https://www.linkedin.com/learning/communication-foundations-2", competencies: ["Communication"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Executive Presence on Video Calls", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/executive-presence-on-video-calls", competencies: ["Communication"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "35 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  { title: "Communicating with Confidence", provider: "LinkedIn Learning", author: "Jeff Ansell", url: "https://www.linkedin.com/learning/communicating-with-confidence", competencies: ["Communication"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 4m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Resource Management
  { title: "Time Management Fundamentals", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/time-management-fundamentals", competencies: ["Resource Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "2h 51m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Managing Multiple Priorities", provider: "LinkedIn Learning", author: "Natasha Bowman", url: "https://www.linkedin.com/learning/managing-multiple-priorities", competencies: ["Resource Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 5m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Budget Basics for Non-Finance Managers", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/budget-basics-for-non-finance-managers", competencies: ["Resource Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 15m", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  // Stakeholder Management
  { title: "Stakeholder Management", provider: "LinkedIn Learning", author: "Frank Saladis", url: "https://www.linkedin.com/learning/stakeholder-management", competencies: ["Stakeholder Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "55 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Influencing Others", provider: "LinkedIn Learning", author: "John Ullmen", url: "https://www.linkedin.com/learning/influencing-others", competencies: ["Stakeholder Management"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 38m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Building Relationships While Working from Home", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/building-relationships-while-working-from-home", competencies: ["Stakeholder Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "28 min", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  // Performance Management
  { title: "Performance Management: Setting Goals and Managing Performance", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/performance-management-setting-goals-and-managing-performance", competencies: ["Performance Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 24m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Giving and Receiving Feedback", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/giving-and-receiving-feedback", competencies: ["Performance Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 2m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Coaching and Mentoring", provider: "LinkedIn Learning", author: "Lisa Earle McLeod", url: "https://www.linkedin.com/learning/coaching-and-mentoring", competencies: ["Performance Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Emotional Intelligence
  { title: "Empathy for Sales Professionals", provider: "LinkedIn Learning", author: "Brenda Bailey-Hughes", url: "https://www.linkedin.com/learning/empathy-for-sales-professionals", competencies: ["Emotional Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "47 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  { title: "Leading with Emotional Intelligence", provider: "LinkedIn Learning", author: "Britt Andreatta", url: "https://www.linkedin.com/learning/leading-with-emotional-intelligence", competencies: ["Emotional Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 13m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Strategic Thinking
  { title: "Strategic Planning Foundations", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/strategic-planning-foundations", competencies: ["Strategic Thinking"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 41m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Business Acumen for Project Managers", provider: "LinkedIn Learning", author: "Bob McGannon", url: "https://www.linkedin.com/learning/business-acumen-for-project-managers", competencies: ["Strategic Thinking"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 18m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Adaptability
  { title: "Embracing Change", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/embracing-change", competencies: ["Adaptability"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "56 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  { title: "Building Resilience", provider: "LinkedIn Learning", author: "Tatiana Kolovou", url: "https://www.linkedin.com/learning/building-resilience", competencies: ["Adaptability"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 8m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Team Leadership
  { title: "Team Leadership", provider: "LinkedIn Learning", author: "Britt Andreatta", url: "https://www.linkedin.com/learning/team-leadership", competencies: ["Team Leadership"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 26m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Building High-Performance Teams", provider: "LinkedIn Learning", author: "Chris Croft", url: "https://www.linkedin.com/learning/building-high-performance-teams", competencies: ["Team Leadership"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "advanced", type: "course", duration_string: "1h 45m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Delegation
  { title: "Delegating Tasks", provider: "LinkedIn Learning", author: "Kevin Eikenberry", url: "https://www.linkedin.com/learning/delegating-tasks", competencies: ["Delegation"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "49 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Delegation and Empowerment", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/delegation-and-empowerment", competencies: ["Delegation"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  // Developing Others
  { title: "Coaching Skills for Leaders and Managers", provider: "LinkedIn Learning", author: "Sara Canaday", url: "https://www.linkedin.com/learning/coaching-skills-for-leaders-and-managers", competencies: ["Developing Others"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 21m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Developing Employees", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/developing-employees", competencies: ["Developing Others"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "57 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Check if already seeded
    const existing = await base44.asServiceRole.entities.LearningResource.filter({ provider: "LinkedIn Learning" });
    if (existing.length > 0) {
      return Response.json({ message: `Already seeded: ${existing.length} courses exist`, skipped: true });
    }

    const results = [];
    for (const course of COURSES) {
      const created = await base44.asServiceRole.entities.LearningResource.create(course);
      results.push(created.id);
    }

    return Response.json({ success: true, created: results.length, ids: results });
  } catch (error) {
    console.error("Seed error:", error.message, error.data || "");
    return Response.json({ error: error.message }, { status: 500 });
  }
});