import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const COURSES = [
  // Situational Intelligence
  { title: "Unconscious Bias", provider: "LinkedIn Learning", author: "Stacey Gordon", url: "https://www.linkedin.com/learning/unconscious-bias", competencies: ["Situational Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "57 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Developing Your Emotional Intelligence", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/developing-your-emotional-intelligence", competencies: ["Situational Intelligence"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Leadership Styles, Behaviors, and Approaches", provider: "LinkedIn Learning", author: "Madecraft", url: "https://www.linkedin.com/learning/leadership-styles-behaviors-and-approaches", competencies: ["Situational Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Decision Making
  { title: "Data-Driven Decisions in Business Operations", provider: "LinkedIn Learning", author: "Lynette Robinson", url: "https://www.linkedin.com/learning/data-driven-decisions-in-business-operations", competencies: ["Decision Making"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "37 min", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Critical Thinking", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/critical-thinking", competencies: ["Decision Making"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "59 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Decision-Making in High-Stress Situations", provider: "LinkedIn Learning", author: "Becki Saltzman", url: "https://www.linkedin.com/learning/decision-making-in-high-stress-situations", competencies: ["Decision Making"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "advanced", type: "course", duration_string: "36 min", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  // Communication
  { title: "Communication Foundations", provider: "LinkedIn Learning", author: "Brenda Bailey-Hughes", url: "https://www.linkedin.com/learning/communication-foundations-2", competencies: ["Communication"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Showing Executive Presence in Person or Remotely", provider: "LinkedIn Learning", author: "Tatiana Kolovou", url: "https://www.linkedin.com/learning/showing-executive-presence-in-person-or-remotely", competencies: ["Communication"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "45 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Communicating with Confidence", provider: "LinkedIn Learning", author: "Jeff Ansell", url: "https://www.linkedin.com/learning/communicating-with-confidence", competencies: ["Communication"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 4m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Resource Management
  { title: "Time Management Fundamentals", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/time-management-fundamentals", competencies: ["Resource Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "2h 51m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Time Management for Managers", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/time-management-for-managers", competencies: ["Resource Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 5m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Finance Foundations", provider: "LinkedIn Learning", author: "Jim Stice", url: "https://www.linkedin.com/learning/finance-foundations-24834241", competencies: ["Resource Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 20m", access: "Subscription", year: 2024, is_active: true, is_premium: true },
  // Stakeholder Management
  { title: "Stakeholder Management for Leaders and Managers", provider: "LinkedIn Learning", author: "Madecraft", url: "https://www.linkedin.com/learning/stakeholder-management-for-leaders-and-managers", competencies: ["Stakeholder Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "55 min", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Influencing Others", provider: "LinkedIn Learning", author: "John Ullmen", url: "https://www.linkedin.com/learning/influencing-others", competencies: ["Stakeholder Management"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 38m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Building Relationships While Working from Home", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/building-relationships-while-working-from-home", competencies: ["Stakeholder Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "28 min", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  // Performance Management
  { title: "Performance Management: Setting Goals and Managing Performance", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/performance-management-setting-goals-and-managing-performance", competencies: ["Performance Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 24m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Giving and Receiving Feedback", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/giving-and-receiving-feedback", competencies: ["Performance Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 2m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Effective Coaching Skills for Leaders Under Pressure", provider: "LinkedIn Learning", author: "Ron Carucci", url: "https://www.linkedin.com/learning/effective-coaching-skills-for-leaders-under-pressure", competencies: ["Performance Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "44 min", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Emotional Intelligence
  { title: "Empathy for Sales Professionals", provider: "LinkedIn Learning", author: "Brenda Bailey-Hughes", url: "https://www.linkedin.com/learning/empathy-for-sales-professionals", competencies: ["Emotional Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "47 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  { title: "Leading with Emotional Intelligence", provider: "LinkedIn Learning", author: "Britt Andreatta", url: "https://www.linkedin.com/learning/leading-with-emotional-intelligence", competencies: ["Emotional Intelligence"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 13m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Strategic Thinking
  { title: "Strategic Planning Foundations", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/strategic-planning-foundations", competencies: ["Strategic Thinking"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 41m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Business Acumen for Project Managers", provider: "LinkedIn Learning", author: "Bob McGannon", url: "https://www.linkedin.com/learning/business-acumen-for-project-managers", competencies: ["Strategic Thinking"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 18m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Adaptability
  { title: "Embracing Change", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/embracing-change", competencies: ["Adaptability"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "56 min", access: "Subscription", year: 2021, is_active: true, is_premium: true },
  { title: "Building Resilience", provider: "LinkedIn Learning", author: "Tatiana Kolovou", url: "https://www.linkedin.com/learning/building-resilience", competencies: ["Adaptability"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 8m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  // Team Leadership
  { title: "Strategies for Effective Leadership Teams", provider: "LinkedIn Learning", author: "Madecraft", url: "https://www.linkedin.com/learning/strategies-for-effective-leadership-teams", competencies: ["Team Leadership"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Building High-Performance Teams", provider: "LinkedIn Learning", author: "Chris Croft", url: "https://www.linkedin.com/learning/building-high-performance-teams", competencies: ["Team Leadership"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "advanced", type: "course", duration_string: "1h 45m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Delegation
  { title: "Delegating Tasks", provider: "LinkedIn Learning", author: "Kevin Eikenberry", url: "https://www.linkedin.com/learning/delegating-tasks", competencies: ["Delegation"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "49 min", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "The Art of Delegation: Become a Better Manager", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/the-art-of-delegation-become-a-better-manager", competencies: ["Delegation"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 14m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  // Developing Others
  { title: "Coaching Skills for Leaders and Managers", provider: "LinkedIn Learning", author: "Sara Canaday", url: "https://www.linkedin.com/learning/coaching-skills-for-leaders-and-managers", competencies: ["Developing Others"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 21m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Coaching and Developing Employees", provider: "LinkedIn Learning", author: "Lisa Gates", url: "https://www.linkedin.com/learning/coaching-and-developing-employees-22657884", competencies: ["Developing Others"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 25m", access: "Subscription", year: 2023, is_active: true, is_premium: true },

  // Collaboration
  { title: "Teamwork Foundations", provider: "LinkedIn Learning", author: "Chris Croft", url: "https://www.linkedin.com/learning/teamwork-foundations-2020", competencies: ["Collaboration"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 15m", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  { title: "Increasing Collaboration on Your Team", provider: "LinkedIn Learning", author: "Daisy Lovelace", url: "https://www.linkedin.com/learning/increasing-collaboration-on-your-team", competencies: ["Collaboration"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "45m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Managing Cross-Functional Collaboration as a Leader", provider: "LinkedIn Learning", author: "Natalie Nixon", url: "https://www.linkedin.com/learning/managing-cross-functional-collaboration-as-a-leader", competencies: ["Collaboration"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "advanced", type: "course", duration_string: "43m", access: "Subscription", year: 2023, is_active: true, is_premium: true },

  // Managing Difficult Conversations
  { title: "Having Difficult Conversations", provider: "LinkedIn Learning", author: "Marlene Chism", url: "https://www.linkedin.com/learning/having-difficult-conversations-2018", competencies: ["Managing Difficult Conversations"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 3m", access: "Subscription", year: 2018, is_active: true, is_premium: true },
  { title: "Conflict Resolution Foundations", provider: "LinkedIn Learning", author: "Lisa Gates", url: "https://www.linkedin.com/learning/conflict-resolution-foundations", competencies: ["Managing Difficult Conversations"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "50m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Partnering with Senior Leaders
  { title: "Managing Up", provider: "LinkedIn Learning", author: "Roberta Matuson", url: "https://www.linkedin.com/learning/managing-up", competencies: ["Partnering with Senior Leaders"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 3m", access: "Subscription", year: 2017, is_active: true, is_premium: true },
  { title: "Developing Executive Presence", provider: "LinkedIn Learning", author: "John Ullmen", url: "https://www.linkedin.com/learning/developing-executive-presence", competencies: ["Partnering with Senior Leaders"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 12m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Psychological Safety Creation
  { title: "Psychological Safety: Clear Blocks to Innovation, Collaboration, and Risk-Taking", provider: "LinkedIn Learning", author: "Derrick Meador", url: "https://www.linkedin.com/learning/psychological-safety-clear-blocks-to-innovation-collaboration-and-risk-taking", competencies: ["Psychological Safety Creation"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "44m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Inclusive Leadership (2022)", provider: "LinkedIn Learning", author: "Dr. Shirley Davis", url: "https://www.linkedin.com/learning/inclusive-leadership-2022", competencies: ["Psychological Safety Creation"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Organizational Impact
  { title: "Leading with Purpose", provider: "LinkedIn Learning", author: "Lisa Earle McLeod", url: "https://www.linkedin.com/learning/leading-with-purpose", competencies: ["Organizational Impact"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "54m", access: "Subscription", year: 2018, is_active: true, is_premium: true },
  { title: "Change Management Foundations", provider: "LinkedIn Learning", author: "Scott Mautz", url: "https://www.linkedin.com/learning/change-management-foundations-10041380", competencies: ["Organizational Impact"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "45m", access: "Subscription", year: 2021, is_active: true, is_premium: true },

  // Ethical Decision-Making & AI Governance
  { title: "Leading Responsible AI in Organizations", provider: "LinkedIn Learning", author: "Elizabeth M. Adams", url: "https://www.linkedin.com/learning/leading-responsible-ai-in-organizations", competencies: ["Ethical Decision-Making & AI Governance"], leadership_level: "Director / Senior Director (enterprise-level strategic oversight, multiple functions, major initiatives)", difficulty_level: "intermediate", type: "course", duration_string: "39m", access: "Subscription", year: 2024, is_active: true, is_premium: true },
  { title: "Ethics in the Age of Generative AI", provider: "LinkedIn Learning", author: "Ronnie Battista", url: "https://www.linkedin.com/learning/ethics-in-the-age-of-generative-ai", competencies: ["Ethical Decision-Making & AI Governance"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "beginner", type: "course", duration_string: "45m", access: "Subscription", year: 2023, is_active: true, is_premium: true },

  // Time and Resource Management
  { title: "Time Management: Working from Home", provider: "LinkedIn Learning", author: "Dave Crenshaw", url: "https://www.linkedin.com/learning/time-management-working-from-home", competencies: ["Time and Resource Management"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 21m", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  { title: "Project Management Foundations", provider: "LinkedIn Learning", author: "Bonnie Biafore", url: "https://www.linkedin.com/learning/project-management-foundations-24819783", competencies: ["Time and Resource Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "2h 11m", access: "Subscription", year: 2023, is_active: true, is_premium: true },

  // Talent Intelligence & Development
  { title: "Talent Management", provider: "LinkedIn Learning", author: "Kathrine Sharon", url: "https://www.linkedin.com/learning/talent-management", competencies: ["Talent Intelligence & Development"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "39m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Human Resources: Strategic Workforce Planning", provider: "LinkedIn Learning", author: "Wayne Cascio", url: "https://www.linkedin.com/learning/human-resources-strategic-workforce-planning-2018", competencies: ["Talent Intelligence & Development"], leadership_level: "Director / Senior Director (enterprise-level strategic oversight, multiple functions, major initiatives)", difficulty_level: "advanced", type: "course", duration_string: "57m", access: "Subscription", year: 2018, is_active: true, is_premium: true },

  // Agile People Operations
  { title: "Agile Foundations", provider: "LinkedIn Learning", author: "Doug Rose", url: "https://www.linkedin.com/learning/agile-foundations", competencies: ["Agile People Operations"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "2h", access: "Subscription", year: 2020, is_active: true, is_premium: true },
  { title: "Scrum: The Basics", provider: "LinkedIn Learning", author: "Kelley O'Connell", url: "https://www.linkedin.com/learning/scrum-the-basics", competencies: ["Agile People Operations"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2017, is_active: true, is_premium: true },

  // Digital and AI Literacy
  { title: "AI Literacy for Business Leaders", provider: "LinkedIn Learning", author: "Pinar Seyhan Demirdag", url: "https://www.linkedin.com/learning/ai-literacy-for-business-leaders", competencies: ["Digital and AI Literacy"], leadership_level: "Director / Senior Director (enterprise-level strategic oversight, multiple functions, major initiatives)", difficulty_level: "intermediate", type: "course", duration_string: "1h 5m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Remote Work Foundations", provider: "LinkedIn Learning", author: "Alexandra Samuel", url: "https://www.linkedin.com/learning/remote-work-foundations-19233235", competencies: ["Digital and AI Literacy"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 12m", access: "Subscription", year: 2023, is_active: true, is_premium: true },

  // Business Acumen
  { title: "Business Acumen for Project Managers", provider: "LinkedIn Learning", author: "Daniel Stanton", url: "https://www.linkedin.com/learning/business-acumen-for-project-managers", competencies: ["Business Acumen"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 22m", access: "Subscription", year: 2017, is_active: true, is_premium: true },
  { title: "Strategic Planning Foundations", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/strategic-planning-foundations", competencies: ["Business Acumen"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 41m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Facilitation & Virtual Collaboration
  { title: "Meeting Facilitation", provider: "LinkedIn Learning", author: "Prakash Raman", url: "https://www.linkedin.com/learning/meeting-facilitation", competencies: ["Facilitation & Virtual Collaboration"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "33m", access: "Subscription", year: 2018, is_active: true, is_premium: true },
  { title: "Managing Virtual Teams", provider: "LinkedIn Learning", author: "Phil Gold", url: "https://www.linkedin.com/learning/managing-virtual-teams-2019", competencies: ["Facilitation & Virtual Collaboration"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "55m", access: "Subscription", year: 2019, is_active: true, is_premium: true },

  // Data Literacy & Evidence-Based Management
  { title: "Data-Driven Decisions in Business Operations", provider: "LinkedIn Learning", author: "Lynette Robinson", url: "https://www.linkedin.com/learning/data-driven-decisions-in-business-operations", competencies: ["Data Literacy & Evidence-Based Management"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "37m", access: "Subscription", year: 2023, is_active: true, is_premium: true },
  { title: "Strategic Human Resources", provider: "LinkedIn Learning", author: "Wayne Cascio", url: "https://www.linkedin.com/learning/strategic-human-resources-2022", competencies: ["Data Literacy & Evidence-Based Management"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "52m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Leadership Agility
  { title: "Leadership Foundations", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/leadership-foundations-2", competencies: ["Leadership Agility"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "2h 5m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Developing Assertive Leadership", provider: "LinkedIn Learning", author: "Madecraft", url: "https://www.linkedin.com/learning/developing-assertive-leadership-2022", competencies: ["Leadership Agility"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "beginner", type: "course", duration_string: "1h", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Learning Agility
  { title: "Growth Mindset", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/growth-mindset", competencies: ["Learning Agility"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "35m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Learning How to Learn New Skills Faster", provider: "LinkedIn Learning", author: "Paul Kirschner", url: "https://www.linkedin.com/learning/learning-how-to-learn-new-skills-faster", competencies: ["Learning Agility"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "52m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Managerial Curiosity
  { title: "Developing a Learning Mindset", provider: "LinkedIn Learning", author: "Gemma Leigh Roberts", url: "https://www.linkedin.com/learning/developing-a-learning-mindset", competencies: ["Managerial Curiosity"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "52m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Innovation Foundations", provider: "LinkedIn Learning", author: "Drew Boyd", url: "https://www.linkedin.com/learning/innovation-foundations", competencies: ["Managerial Curiosity"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 4m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Personal Integrity & Ethics
  { title: "Ethics and Law", provider: "LinkedIn Learning", author: "Bob McGannon", url: "https://www.linkedin.com/learning/ethics-and-law", competencies: ["Personal Integrity & Ethics"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 2m", access: "Subscription", year: 2019, is_active: true, is_premium: true },
  { title: "Accountability and Employee Ownership", provider: "LinkedIn Learning", author: "Mike Figliuolo", url: "https://www.linkedin.com/learning/accountability-and-employee-ownership", competencies: ["Personal Integrity & Ethics"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 10m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Cognitive Flexibility
  { title: "Design Thinking: Understanding the Process", provider: "LinkedIn Learning", author: "Turi McKinley", url: "https://www.linkedin.com/learning/design-thinking-understanding-the-process", competencies: ["Cognitive Flexibility"], leadership_level: "Mid-Level Manager (managers of managers, experienced team leads, functional leads)", difficulty_level: "intermediate", type: "course", duration_string: "1h 11m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Problem Solving Techniques", provider: "LinkedIn Learning", author: "Chris Croft", url: "https://www.linkedin.com/learning/problem-solving-techniques", competencies: ["Cognitive Flexibility"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 32m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Transition from IC to Leader
  { title: "New Manager Foundations", provider: "LinkedIn Learning", author: "Todd Dewett", url: "https://www.linkedin.com/learning/new-manager-foundations-2", competencies: ["Transition from IC to Leader"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 47m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Becoming a Manager", provider: "LinkedIn Learning", author: "Coursera", url: "https://www.linkedin.com/learning/becoming-a-manager", competencies: ["Transition from IC to Leader"], leadership_level: "Individual Contributor to First-Time Manager (entry-level leaders, frontline managers, new supervisors)", difficulty_level: "beginner", type: "course", duration_string: "1h 20m", access: "Subscription", year: 2022, is_active: true, is_premium: true },

  // Systems Thinking
  { title: "Systems Thinking", provider: "LinkedIn Learning", author: "Curt Savage", url: "https://www.linkedin.com/learning/systems-thinking", competencies: ["Systems Thinking"], leadership_level: "Senior Manager / Business Unit Leader (leads larger teams, cross-functional groups, or business units)", difficulty_level: "intermediate", type: "course", duration_string: "1h 8m", access: "Subscription", year: 2022, is_active: true, is_premium: true },
  { title: "Decision-Making Strategies", provider: "LinkedIn Learning", author: "Dorie Clark", url: "https://www.linkedin.com/learning/decision-making-strategies", competencies: ["Systems Thinking"], leadership_level: "Director / Senior Director (enterprise-level strategic oversight, multiple functions, major initiatives)", difficulty_level: "advanced", type: "course", duration_string: "1h 4m", access: "Subscription", year: 2021, is_active: true, is_premium: true },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Delete all existing LinkedIn Learning records first
    const existing = await base44.asServiceRole.entities.LearningResource.filter({ provider: "LinkedIn Learning" }, null, 100);
    let deleted = 0;
    for (const record of existing) {
      await base44.asServiceRole.entities.LearningResource.delete(record.id);
      deleted++;
    }

    // Create fresh records
    const results = [];
    for (const course of COURSES) {
      const created = await base44.asServiceRole.entities.LearningResource.create(course);
      results.push(created.id);
    }

    return Response.json({ success: true, deleted, created: results.length });
  } catch (error) {
    console.error("Seed error:", error.message, error.data || "");
    return Response.json({ error: error.message }, { status: 500 });
  }
});